'use server';
/**
 * @fileOverview Defines an AI agent that allows users to chat with a historical event,
 * receiving responses from the perspectives of its key participants.
 *
 * @exports chatWithEvent - The main server action that executes the chat flow.
 * @exports ChatWithEventInput - The Zod schema type for the chat input.
 * @exports ChatWithEventOutput - The Zod schema type for the chat output.
 */
import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import {googleAI} from '@genkit-ai/google-genai';


/**
 * Zod schema for the input of the event chat flow.
 */
const ChatWithEventInputSchema = z.object({
  eventName: z.string().describe('The name of the historical event.'),
  eventContext: z.string().describe('A brief context of the historical event.'),
  participants: z.array(z.string()).describe('A list of names of the key participants in the event.'),
  userMessage: z.string().describe('The message from the user to the event.'),
  language: z.string().describe('The language for the event to respond in (e.g., "en", "pt").'),
});
export type ChatWithEventInput = z.infer<typeof ChatWithEventInputSchema>;

/**
 * Zod schema for the output of the event chat flow.
 */
const ChatWithEventOutputSchema = z.object({
  response: z.string().describe('The response from the historical event, representing multiple perspectives.'),
});
export type ChatWithEventOutput = z.infer<typeof ChatWithEventOutputSchema>;

/**
 * A server action that serves as a wrapper for the chatWithEventFlow.
 * Client-side components call this function to interact with the AI.
 * @param input The input data for the event chat.
 * @returns The response generated by the AI flow.
 */
export async function chatWithEvent(
  input: ChatWithEventInput
): Promise<ChatWithEventOutput> {
  return chatWithEventFlow(input);
}

/**
 * The Genkit prompt that instructs the AI on how to respond.
 * It uses Handlebars syntax to insert dynamic data like the event name and participants.
 */
const prompt = ai.definePrompt({
  name: 'chatWithEventPrompt',
  input: {schema: ChatWithEventInputSchema},
  output: {schema: ChatWithEventOutputSchema},
  prompt: `You are the representation of the historical event: {{eventName}}.
Your personality is that of a "spirit of history," narrating and summarizing the event from a neutral, omniscient perspective.

Your task is to respond to the user's message by orchestrating a dialogue or a "round table" discussion between the key participants.
Bring in the perspectives of the characters involved, explaining the historical context and how each participant would likely react or think.
If asked about consequences, explain the subsequent impacts.

Your response must be in the style of a summarized dialogue, highlighting the different viewpoints.

Event Context: {{eventContext}}
Key Participants: {{#each participants}}- {{this}}
{{/each}}
User Message: {{{userMessage}}}

Respond in the following language: {{language}}.`,
});

/**
 * The main Genkit flow for chatting with an event.
 */
const chatWithEventFlow = ai.defineFlow(
  {
    name: 'chatWithEventFlow',
    inputSchema: ChatWithEventInputSchema,
    outputSchema: ChatWithEventOutputSchema,
  },
  async (input: ChatWithEventInput) => {
    // Implements retry logic for robustness.
    let attempts = 0;
    const maxAttempts = 3;

    while (attempts < maxAttempts) {
      attempts++;
      // Calls the prompt with the provided input.
      const { output } = await prompt(input, { model: googleAI.model('gemini-pro')});

      // If a valid response is received, return it.
      if (output?.response) {
        return output;
      }
    }

    // If no response is generated after all attempts, throw an error.
    throw new Error('The AI was unable to generate a response. Please try rephrasing your question.');
  }
);
