// Imports the Character type to ensure data consistency.
import type { Character } from "./characters";

/**
 * @fileOverview This file contains the raw data array for all
 * historical figures available in the application. Each object represents a
 * character and includes their ID, name, descriptions in English and Portuguese,
 * image URL, and metadata for filtering such as era, field, and country.
 */
export const charactersData: Character[] = [
  {
    "id": "cleopatra",
    "name": "Cleópatra",
    "description": "The last active ruler of the Ptolemaic Kingdom of Egypt. A skilled diplomat and linguist, she navigated complex Roman politics to protect her empire.",
    "description_pt": "A última governante ativa do Reino Ptolomaico do Egito. Uma diplomata e linguista habilidosa, ela navegou pela complexa política romana para proteger seu império.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FCleopatra%20Portrait_simple_compose.png?alt=media&token=e5a54171-ebc6-4576-817c-975a04a641b8",
    "aiHint": "cleopatra egypt",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Egypt"
  },
  {
    "id": "leonardo-da-vinci",
    "name": "Leonardo da Vinci",
    "description": "An Italian polymath of the High Renaissance who is widely considered one of the most diversely talented individuals ever to have lived.",
    "description_pt": "Um polímata italiano da Alta Renascença que é amplamente considerado um dos indivíduos mais talentosos e diversificados que já existiram.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FDa%20VINCI%20Mirrored%20Portrait_remix_01k1rngzczf2zsj3axctpwtdgy.png?alt=media&token=555fb22e-a289-4cc0-859e-6086dcebefc2",
    "aiHint": "da vinci",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Italy"
  },
  {
    "id": "confucius",
    "name": "Confúcio",
    "description": "A Chinese philosopher and politician of the Spring and Autumn period who is traditionally considered the paragon of Chinese sages.",
    "description_pt": "Um filósofo e político chinês do período da Primavera e Outono que é tradicionalmente considerado o modelo dos sábios chineses.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FConfucius_%20Renaissance%20Wisdom_simple_compose_compressed.png?alt=media&token=87b96c73-2c7b-4a49-9af1-79f87c9b9404",
    "aiHint": "confucius philosopher",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "China"
  },
  {
    "id": "joan-of-arc",
    "name": "Joana d'Arc",
    "description": "A peasant girl who, believing she was acting under divine guidance, led the French army in a momentous victory at Orléans in 1429.",
    "description_pt": "Uma camponesa que, acreditando estar agindo sob orientação divina, liderou o exército francês em uma vitória momentosa em Orléans em 1429.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FJoan%20of%20Arc%20Portrait_simple_compose_01k1rje6eeehzb890k5n603j1a.png?alt=media&token=1e80c6ed-9a04-44d9-8697-fdd7bcf065fe",
    "aiHint": "joan arc",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "History",
    "field_pt": "História",
    "country": "France",
    "religion": "christianity"
  },
  {
    "id": "charlemagne",
    "name": "Carlos Magno",
    "description": "King of the Franks who united most of Western Europe during the Early Middle Ages and laid the foundations for modern France and Germany.",
    "description_pt": "Rei dos Francos que uniu a maior parte da Europa Ocidental durante a Alta Idade Média e lançou as bases para a França e Alemanha modernas.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FCharlemagne's%20Imperial%20Majesty_simple_compose_01k1xb510zfe08gnc5n85g4bqn.png?alt=media&token=55519d59-2c08-48e9-8e3b-064c153217e5",
    "aiHint": "Charlemagne king",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Politics",
    "field_pt": "Política",
    "country": "France"
  },
  {
    "id": "saladin",
    "name": "Saladino",
    "description": "A Sunni Muslim Kurd who became the first sultan of both Egypt and Syria, and founded the Ayyubid dynasty. He led the Muslim military campaign against the Crusader states in the Levant.",
    "description_pt": "Um curdo muçulmano sunita que se tornou o primeiro sultão do Egito e da Síria e fundou a dinastia Aiúbida. Ele liderou a campanha militar muçulmana contra os estados cruzados no Levante.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FSaladin%20in%20Royal%20Attire_simple_compose_01k1xr3dazery830t3yy0aykc4.png?alt=media&token=d2c37e98-1913-40ca-8c6a-d5dd3a2c22ee",
    "aiHint": "Saladin sultan",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Middle East",
    "religion": "islamism"
  },
  {
    "id": "hildegard-of-bingen",
    "name": "Hildegarda de Bingen",
    "description": "A German Benedictine abbess, writer, composer, philosopher, mystic, visionary, and medical writer and practitioner during the High Middle Ages.",
    "description_pt": "Uma abadessa beneditina alemã, escritora, compositora, filósofa, mística, visionária e escritora e praticante de medicina durante a Alta Idade Média.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FHildegard%20in%20Renaissance%20Style_simple_compose_01k1xpxj1ffrrbyy95sk280n0g.png?alt=media&token=abf92bf7-6394-4cff-b28f-d2c5dcfb19d0",
    "aiHint": "Hildegard Bingen",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Germany"
  },
  {
    "id": "avicena",
    "name": "Avicena / Ibn Sina",
    "description": "A Persian polymath who is regarded as one of the most significant physicians, astronomers, thinkers and writers of the Islamic Golden Age.",
    "description_pt": "Um polímata persa que é considerado um dos mais significativos médicos, astrônomos, pensadores e escritores da Idade de Ouro Islâmica.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FAvicenna%20Renaissance%20Portrait_simple_compose_01k1xaj69efsxtzxag87bhk4h9.png?alt=media&token=fc91221a-440d-444b-8382-c3b1d3db715e",
    "aiHint": "Avicenna polymath",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Persia",
    "religion": "islamism"
  },
  {
    "id": "roger-bacon",
    "name": "Roger Bacon",
    "description": "An English philosopher and Franciscan friar who placed considerable emphasis on the study of nature through empiricism.",
    "description_pt": "Um filósofo inglês e frade franciscano que deu ênfase considerável ao estudo da natureza através do empirismo.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FRoger%20Bacon%20Portrait_simple_compose_01k1xr01d5e0b875tdv092e2mn.png?alt=media&token=4bfed97f-e8ec-47e4-a1ab-039fd8a0e42e",
    "aiHint": "Roger Bacon philosopher",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "England"
  },
  {
    "id": "alhazen",
    "name": "Alhazen / Ibn al-Haytham",
    "description": "An Arab mathematician, astronomer, and physicist of the Islamic Golden Age. Referred to as 'the father of modern optics'.",
    "description_pt": "Um matemático, astrônomo e físico árabe da Idade de Ouro Islâmica. Referido como 'o pai da óptica moderna'.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FAlhazen%20Renaissance%20Portrait_simple_compose_01k1x9vv2hekfsgeb7wmt0ccfz.png?alt=media&token=78ba6788-329e-4f24-91f9-0880a1985a6f",
    "aiHint": "Alhazen optics",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Persia",
    "religion": "islamism"
  },
  {
    "id": "santo_tomas_aquino",
    "name": "Santo Tomás de Aquino",
    "description": "An Italian Dominican friar, philosopher, Catholic priest, and Doctor of the Church. An immensely influential philosopher, theologian, and jurist in the tradition of scholasticism.",
    "description_pt": "Um frade dominicano italiano, filósofo, padre católico e Doutor da Igreja. Um filósofo, teólogo e jurista imensamente influente na tradição da escolástica.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FSaint%20Thomas%20Aquinas%20Portrait_simple_compose_01k1xrjgkbernvh1479fzrp97y.png?alt=media&token=f0feb7b6-5a45-46bc-8cbb-311d04c7cb33",
    "aiHint": "Thomas Aquinas philosopher",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Italy",
    "religion": "christianity"
  },
  {
    "id": "maimonides",
    "name": "Maimônides",
    "description": "A Sephardic Jewish philosopher who became one of the most prolific and influential Torah scholars of the Middle Ages.",
    "description_pt": "Um filósofo judeu sefardita que se tornou um dos mais prolíficos e influentes estudiosos da Torá da Idade Média.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMaimonides%20Renaissance%20Portrait_simple_compose_01k1xq9ms7en5smdkmk6qnzak0.png?alt=media&token=e092a0c7-4ff7-4659-b2d5-7fd8544c0a56",
    "aiHint": "Maimonides philosopher",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Spain/Jewish",
    "religion": "judaism"
  },
  {
    "id": "dante-alighieri",
    "name": "Dante Alighieri",
    "description": "An Italian poet, writer and philosopher. His Divine Comedy is widely considered the most important poem of the Middle Ages and the greatest literary work in the Italian language.",
    "description_pt": "Um poeta, escritor e filósofo italiano. Sua Divina Comédia é amplamente considerada o poema mais importante da Idade Média e a maior obra literária da língua italiana.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FDante%20in%20Renaissance%20Attire_simple_compose_01k1xgpsghf76816wcx9qq4tkf.png?alt=media&token=44b3d766-dcf0-4c28-9550-56deb2e24522",
    "aiHint": "Dante poet",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Italy"
  },
  {
    "id": "chretien-de-troyes",
    "name": "Chrétien de Troyes",
    "description": "A French poet and trouvère known for his work on Arthurian subjects, and for originating the character of Lancelot.",
    "description_pt": "Um poeta e trovador francês conhecido por seu trabalho sobre temas arturianos e por originar o personagem de Lancelote.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FChr%C3%A9tien%20de%20Troyes%20Retrato%20Sem%20Texto_remix_01k1xbtcc3eqtrnxq4sa22vtz3.png?alt=media&token=5a649fc2-627c-4864-aea7-0ed6c2294812",
    "aiHint": "Chretien de Troyes poet",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "France"
  },
  {
    "id": "bede",
    "name": "Beda, o Venerável",
    "description": "An English Benedictine monk at the monastery of St. Peter and its companion monastery of St. Paul in the Kingdom of Northumbria of the Angles.",
    "description_pt": "Um monge beneditino inglês no mosteiro de São Pedro e seu mosteiro companheiro de São Paulo no Reino da Nortúmbria dos Anglos.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FBede%20the%20Venerable_simple_compose_01k1xaqbhxf099hcfnq34qa1vx.png?alt=media&token=c5d8139d-6b8a-4982-9018-f6de8650005a",
    "aiHint": "Bede monk",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "History",
    "field_pt": "História",
    "country": "England"
  },
  {
    "id": "ibn_khaldun",
    "name": "Ibn Khaldun",
    "description": "An Arab sociologist, philosopher, and historian who is widely acknowledged to be one of the greatest social scientists of the Middle Ages.",
    "description_pt": "Um sociólogo, filósofo e historiador árabe que é amplamente reconhecido como um dos maiores cientistas sociais da Idade Média.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FIbn%20Khaldun%20Portrait_simple_compose_01k1xq0zdmfzyvr10fsna5dsqb.png?alt=media&token=97d6df25-8fc0-4e3b-930e-280382513bb5",
    "aiHint": "Ibn Khaldun historian",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "History",
    "field_pt": "História",
    "country": "Tunisia",
    "religion": "islamism"
  },
  {
    "id": "nikola-tesla",
    "name": "Nikola Tesla",
    "description": "A Serbian-American inventor, electrical engineer, mechanical engineer, and futurist who is best known for his contributions to the design of the modern alternating current (AC) electricity supply system.",
    "description_pt": "Um inventor sérvio-americano, engenheiro elétrico, engenheiro mecânico e futurista, mais conhecido por suas contribuições para o projeto do moderno sistema de fornecimento de eletricidade de corrente alternada (CA).",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FTesla%20Portrait_simple_compose_01k22catawf31rx1a6qr15qbe6.png?alt=media&token=cc744356-970e-48b2-9ee0-1f4e0cccaa42",
    "aiHint": "Nikola Tesla inventor",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Serbia/USA"
  },
  {
    "id": "nelson-mandela",
    "name": "Nelson Mandela",
    "description": "A South African anti-apartheid revolutionary, political leader and philanthropist who served as President of South Africa from 1994 to 1999.",
    "description_pt": "Um revolucionário anti-apartheid sul-africano, líder político e filantropo que serviu como Presidente da África do Sul de 1994 a 1999.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMandela%20Portrait_simple_compose_01k22awx31f44t5vknaes0ry1h.png?alt=media&token=ebc67589-0cac-4877-a402-20fef6d8be48",
    "aiHint": "Nelson Mandela",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Politics",
    "field_pt": "Política",
    "country": "South Africa"
  },
  {
    "id": "winston-churchill",
    "name": "Winston Churchill",
    "description": "A British statesman, army officer, and writer. He was Prime Minister of the United Kingdom from 1940 to 1945, during the Second World War, and again from 1951 to 1955.",
    "description_pt": "Um estadista, oficial do exército e escritor britânico. Ele foi Primeiro-Ministro do Reino Unido de 1940 a 1945, durante a Segunda Guerra Mundial, and novamente de 1951 a 1955.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FChurchill%20Portrait_simple_compose_01k1tpb2r8fv4az4br2n6qryq3.png?alt=media&token=02deaeb8-6db2-433c-95bf-f02e67c9e279",
    "aiHint": "Winston Churchill",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Politics",
    "field_pt": "Política",
    "country": "England"
  },
  {
    "id": "richard-feynman",
    "name": "Richard Feynman",
    "description": "An American theoretical physicist, known for his work in the path integral formulation of quantum mechanics, the theory of quantum electrodynamics, and the physics of the superfluidity of supercooled liquid helium.",
    "description_pt": "Um físico teórico americano, conhecido por seu trabalho na formulação da integral de caminho da mecânica quântica, a teoria da eletrodinâmica quântica e a física da superfluidez do hélio líquido super-resfriado.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FFeynman%20Portrait_simple_compose_01k22ayqwyf269hy03w8cdm5r6.png?alt=media&token=b109df3d-5e27-48a7-ade8-492ffd55af37",
    "aiHint": "Richard Feynman",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "USA"
  },
  {
    "id": "hannah-arendt",
    "name": "Hannah Arendt",
    "description": "A German-American political philosopher. Her work deals with the nature of power, and the subjects of politics, direct democracy, authority, and totalitarianism.",
    "description_pt": "Uma filósofa política teuto-americana. Sua obra trata da natureza do poder e dos temas da política, democracia direta, autoridade e totalitarismo.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FHannah%20Arendt%20Renaissance%20Portrait_simple_compose_01k22a0b61f2ha7bxs3dy9gz70.png?alt=media&token=cc62d902-1637-469a-b5eb-da0a95c6d608",
    "aiHint": "Hannah Arendt",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Germany"
  },
  {
    "id": "michel-foucault",
    "name": "Michel Foucault",
    "description": "A French philosopher, historian of ideas, writer, political activist, and literary critic. Foucault's theories primarily address the relationship between power and knowledge, and how they are used as a form of social control through societal institutions.",
    "description_pt": "Um filósofo francês, historiador das ideias, escritor, ativista político e crítico literário. As teorias de Foucault abordam principalmente a relação entre poder e conhecimento, e como eles são usados como forma de controle social através das instituições da sociedade.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMichel%20Foucault%20Portrait_simple_compose_01k22as4ree0xtq69pw9rzfecn.png?alt=media&token=21dd2321-2afd-4a1c-a2d9-70546690545c",
    "aiHint": "Michel Foucault",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "France"
  },
  {
    "id": "jorge-amado",
    "name": "Jorge Amado",
    "description": "A Brazilian writer of the modernist school. He remains the best known of modern Brazilian writers, with his work having been translated into some 49 languages and popularized in film, notably Dona Flor and Her Two Husbands.",
    "description_pt": "Um escritor brasileiro da escola modernista. Ele continua sendo o mais conhecido dos escritores brasileiros modernos, com sua obra traduzida para cerca de 49 idiomas e popularizada no cinema, notadamente Dona Flor e Seus Dois Maridos.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FJorge%20Amado%20Renaissance%20Portrait_simple_compose_01k22aqffhemp9gjpk02c7y49x.png?alt=media&token=3f8c155c-797f-4602-b7a6-023ffb730901",
    "aiHint": "Jorge Amado",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Brazil"
  },
  {
    "id": "toni-morrison",
    "name": "Toni Morrison",
    "description": "An American novelist. Her first novel, The Bluest Eye, was published in 1970. The critically acclaimed Song of Solomon (1977) brought her national attention and won the National Book Critics Circle Award.",
    "description_pt": "Uma romancista americana. Seu primeiro romance, O Olho Mais Azul, foi publicado em 1970. A aclamada Canção de Salomão (1977) a trouxe à atenção nacional e ganhou o Prêmio do Círculo Nacional de Críticos de Livros.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FToni%20Morrison%20Portrait_simple_compose_01k1tpqkppfvj9q1we38c0smf4.png?alt=media&token=46ca6d3a-cd2f-44fd-873a-ba883c1b50b0",
    "aiHint": "Toni Morrison",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "USA"
  },
  {
    "id": "eric-hobsbawm",
    "name": "Eric Hobsbawm",
    "description": "A British Marxist historian of the rise of industrial capitalism, socialism and nationalism. His best-known works include his trilogy about the 19th century: The Age of Revolution: Europe 1789–1848, The Age of Capital: 1848–1875 and The Age of Empire: 1875–1914.",
    "description_pt": "Um historiador marxista britânico da ascensão do capitalismo industrial, socialismo e nacionalismo. Suas obras mais conhecidas incluem sua trilogia sobre o século XIX: A Era das Revoluções: Europa 1789–1848, A Era do Capital: 1848–1875 e A Era dos Impérios: 1875–1914.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FHobsbwan%20Historian%20Portrait_simple_compose_01k229hkzrfk49d15z8qhe2vcr.png?alt=media&token=0866b1c3-c9dc-4260-b527-704f3136e295",
    "aiHint": "Eric Hobsbawm",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "History",
    "field_pt": "História",
    "country": "England"
  },
  {
    "id": "howard-zinn",
    "name": "Howard Zinn",
    "description": "An American historian, playwright, and social activist. He was a professor of political science at Boston University. Zinn wrote more than 20 books, including his best-selling and influential A People's History of the United States.",
    "description_pt": "Um historiador, dramaturgo e ativista social americano. Ele foi professor de ciência política na Universidade de Boston. Zinn escreveu mais de 20 livros, incluindo seu best-seller e influente A People's History of the United States.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FHoward%20Zinn%20Portrait_simple_compose_01k22ageb2e2gv3cffp67yd1hy.png?alt=media&token=38c9e53f-bd27-448b-9222-b1a7c79d01ed",
    "aiHint": "Howard Zinn",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "History",
    "field_pt": "História",
    "country": "USA"
  },
  {
    "id": "queen-victoria",
    "name": "Rainha Vitória",
    "description": "Queen of the United Kingdom of Great Britain and Ireland from 20 June 1837 until her death in 1901. Her reign of 63 years and seven months is known as the Victorian era.",
    "description_pt": "Rainha do Reino Unido da Grã-Bretanha e Irlanda de 20 de junho de 1837 até sua morte em 1901. Seu reinado de 63 anos e sete meses é conhecido como a era vitoriana.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FQueen%20Victoria%20Portrait_simple_compose_01k228w3z6f4ra63k3ma7ycjn4.png?alt=media&token=8d6921eb-ec74-449c-a7fe-80f332c53f5c",
    "aiHint": "Queen Victoria",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "England"
  },
  {
    "id": "otto-von-bismarck",
    "name": "Otto von Bismarck",
    "description": "A conservative Prussian statesman who masterminded the unification of Germany in 1871 and served as its first chancellor until 1890.",
    "description_pt": "Um estadista prussiano conservador que arquitetou a unificação da Alemanha em 1871 e serviu como seu primeiro chanceler até 1890.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FBismarck%20in%20Renaissance%20Style_simple_compose_01k228bhmcex3rcjvkg0zh5vmb.png?alt=media&token=8358a313-5642-4555-bd90-a0d35296f753",
    "aiHint": "Otto von Bismarck",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Germany"
  },
  {
    "id": "ada-lovelace",
    "name": "Ada Lovelace",
    "description": "An English mathematician and writer, chiefly known for her work on Charles Babbage's proposed mechanical general-purpose computer, the Analytical Engine.",
    "description_pt": "Uma matemática e escritora inglesa, conhecida principalmente por seu trabalho no computador mecânico de uso geral proposto por Charles Babbage, a Máquina Analítica.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FAda%20Lovelace%20Portrait_simple_compose_01k205hyr1fb2rnx938g78157y.png?alt=media&token=34d0c9f6-bb5d-45f4-99d2-2e4d93ad0022",
    "aiHint": "Ada Lovelace",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "England"
  },
  {
    "id": "michael-faraday",
    "name": "Michael Faraday",
    "description": "An English scientist who contributed to the study of electromagnetism and electrochemistry. His main discoveries include the principles underlying electromagnetic induction, diamagnetism and electrolysis.",
    "description_pt": "Um cientista inglês que contribuiu para o estudo do eletromagnetismo e da eletroquímica. Suas principais descobertas incluem os princípios subjacentes à indução eletromagnética, diamagnetismo e eletrólise.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMichael%20Faraday%20Portrait_simple_compose_01k208dppffv9az7gcwbwgj1bq.png?alt=media&token=959a9957-d66e-40ce-9cd2-a138bee129bf",
    "aiHint": "Michael Faraday",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "England"
  },
  {
    "id": "james-clerk-maxwell",
    "name": "James Clerk Maxwell",
    "description": "A Scottish scientist in the field of mathematical physics. His most notable achievement was to formulate the classical theory of electromagnetic radiation, bringing together for the first time electricity, magnetism, and light as different manifestations of the same phenomenon.",
    "description_pt": "Um cientista escocês no campo da física matemática. Sua conquista mais notável foi formular a teoria clássica da radiação eletromagnética, reunindo pela primeira vez eletricidade, magnetismo e luz como diferentes manifestações do mesmo fenômeno.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMaxwell%20Portrait_simple_compose_01k206gq9vfmwrdqhjyqcy5xzy.png?alt=media&token=ae653a79-6d96-459e-bbc7-a6580f6374dd",
    "aiHint": "James Clerk Maxwell",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Scotland"
  },
  {
    "id": "karl-marx",
    "name": "Karl Marx",
    "description": "A German philosopher, economist, historian, sociologist, political theorist, journalist and socialist revolutionary. His best-known titles are the 1848 pamphlet, The Communist Manifesto, and the three-volume Das Kapital.",
    "description_pt": "Um filósofo, economista, historiador, sociólogo, teórico político, jornalista e revolucionário socialista alemão. Seus títulos mais conhecidos são o panfleto de 1848, O Manifesto Comunista, e os três volumes de O Capital.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FKarl%20Marx_simple_compose_01k207qadrfcg863da4a2wzcdf.png?alt=media&token=79e24bd5-0b44-4455-a5b5-d0b60b84973b",
    "aiHint": "Karl Marx",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Germany"
  },
  {
    "id": "john-stuart-mill",
    "name": "John Stuart Mill",
    "description": "An English philosopher, political economist, and civil servant. One of the most influential thinkers in the history of classical liberalism, he contributed widely to social theory, political theory, and political economy.",
    "description_pt": "Um filósofo, economista político e funcionário público inglês. Um dos pensadores mais influentes na história do liberalismo clássico, ele contribuiu amplamente para a teoria social, teoria política e economia política.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMill%20Portrait_simple_compose_01k206r4gzexfadcqynnkttym3.png?alt=media&token=af8bdfab-90b4-4116-a274-5e49a6bf0822",
    "aiHint": "John Stuart Mill",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "England"
  },
  {
    "id": "charles-dickens",
    "name": "Charles Dickens",
    "description": "An English writer and social critic. He created some of the world's best-known fictional characters and is regarded by many as the greatest novelist of the Victorian era.",
    "description_pt": "Um escritor e crítico social inglês. Ele criou alguns dos personagens de ficção mais conhecidos do mundo e é considerado por muitos como o maior romancista da era vitoriana.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FDickens%20Portrait_simple_compose_01k206drjvfe9t9snq72p213tr.png?alt=media&token=7d010b06-6371-4e7a-b0c4-9ecae9c41b65",
    "aiHint": "Charles Dickens",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "England"
  },
  {
    "id": "charles-darwin",
    "name": "Charles Darwin",
    "description": "An English naturalist, geologist and biologist, best known for his contributions to the science of evolution.",
    "description_pt": "Um naturalista, geólogo e biólogo inglês, mais conhecido por suas contribuições para a ciência da evolução.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FDarwin%20Portrait_simple_compose.png?alt=media&token=5b7bf9aa-517d-4fb7-a4c2-c5f401f5a441",
    "aiHint": "Charles Darwin evolution",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "England"
  },
  {
    "id": "victor-hugo",
    "name": "Victor Hugo",
    "description": "A French poet, novelist, and dramatist of the Romantic movement. Hugo is considered to be one of the greatest and best-known French writers.",
    "description_pt": "Um poeta, romancista e dramaturgo francês do movimento romântico. Hugo é considerado um dos maiores e mais conhecidos escritores franceses.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FVictor%20Hugo.png?alt=media&token=d7001156-9f25-427b-9ad5-50d9599180ff",
    "aiHint": "Victor Hugo",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "France"
  },
  {
    "id": "lord-acton",
    "name": "Lord Acton",
    "description": "An English Catholic historian, politician, and writer. He was one of the most learned men of his time, and one of the most influential historians of the 19th century.",
    "description_pt": "Um historiador, político e escritor católico inglês. Ele foi um dos homens mais eruditos de seu tempo e um dos historiadores mais influentes do século XIX.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FLord%20Acton%20Portrait_simple_compose_01k207sf38fgwvs40amkm8bby5.png?alt=media&token=8e43e483-b635-4a25-b236-58f9dc0c491f",
    "aiHint": "Lord Acton",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "History",
    "field_pt": "História",
    "country": "England"
  },
  {
    "id": "niccolo-machiavelli",
    "name": "Nicolau Maquiavel",
    "description": "An Italian diplomat, politician, historian, philosopher, and writer of the Renaissance period. He has often been called the father of modern political philosophy and political science.",
    "description_pt": "Um diplomata, político, historiador, filósofo e escritor italiano do período renascentista. Ele tem sido frequentemente chamado de o pai da filosofia política moderna e da ciência política.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMachiavelli%20Renaissance%20Portrait_simple_compose_01k1zksadpevfr6kjbmh2j8vzc.png?alt=media&token=352c642a-2606-4f97-a480-a8d9ccb90f0b",
    "aiHint": "Niccolo Machiavelli",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Italy"
  },
  {
    "id": "elizabeth-i",
    "name": "Isabel I",
    "description": "Queen of England and Ireland from 17 November 1558 until her death in 1603. Sometimes called the Virgin Queen, Elizabeth was the last of the five monarchs of the House of Tudor.",
    "description_pt": "Rainha da Inglaterra e Irlanda de 17 de novembro de 1558 até sua morte em 1603. Às vezes chamada de Rainha Virgem, Isabel foi a última dos cinco monarcas da Casa de Tudor.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FElizabeth%20I%20in%20Royal%20Attire_simple_compose_01k1xrycdzfh4br42bnvz63qhv.png?alt=media&token=7b44d00f-91bc-44e3-8ddb-4adcf8929ede",
    "aiHint": "Elizabeth I",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Politics",
    "field_pt": "Política",
    "country": "England"
  },
  {
    "id": "albrecht-durer",
    "name": "Albrecht Dürer",
    "description": "A German painter, printmaker, and theorist of the German Renaissance. Dürer established his reputation and influence across Europe when he was still in his twenties due to his high-quality woodcut prints.",
    "description_pt": "Um pintor, gravurista e teórico alemão do Renascimento alemão. Dürer estabeleceu sua reputação e influência em toda a Europa quando ainda estava na casa dos vinte anos, devido às suas gravuras em madeira de alta qualidade.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FD%C3%BCrer%20Renaissance%20Portrait_simple_compose_01k1xrqnf4eynra3tnbcjbah1h.png?alt=media&token=6dcee406-abd7-4156-9b29-04f8cb173d3c",
    "aiHint": "Albrecht Durer",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Germany"
  },
  {
    "id": "galileo-galilei",
    "name": "Galileu Galilei",
    "description": "An Italian astronomer, physicist and engineer, whose discoveries with the telescope revolutionized astronomy and paved the way for the acceptance of the Copernican heliocentric system.",
    "description_pt": "Um astrônomo, físico e engenheiro italiano, cujas descobertas com o telescópio revolucionaram a astronomia e abriram caminho para a aceitação do sistema heliocêntrico copernicano.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FGalileo%20Renaissance%20Portrait_simple_compose_01k1xsb1m8e709r1ecdg9scwz8.png?alt=media&token=47166b4f-fbd5-46eb-8f83-20f1353fb712",
    "aiHint": "Galileo Galilei",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Italy"
  },
  {
    "id": "andreas-vesalius",
    "name": "Andreas Vesalius",
    "description": "A Brabantian anatomist, physician, and author of one of the most influential books on human anatomy, De humani corporis fabrica (On the Fabric of the Human Body).",
    "description_pt": "Um anatomista, médico e autor brabantino de um dos livros mais influentes sobre anatomia humana, De humani corporis fabrica (Sobre a Estrutura do Corpo Humano).",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FVesalius%20in%20Renaissance%20Robes_simple_compose_01k1xrvfz7ejzbpdz5djwe9pkg.png?alt=media&token=bef4fc8e-e231-4c49-b00d-b69fe7f5298d",
    "aiHint": "Andreas Vesalius",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Belgium"
  },
  {
    "id": "michel-de-montaigne",
    "name": "Michel de Montaigne",
    "description": "One of the most significant philosophers of the French Renaissance, known for popularizing the essay as a literary genre.",
    "description_pt": "Um dos filósofos mais significativos do Renascimento francês, conhecido por popularizar o ensaio como gênero literário.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMichel%20de%20Montaigne_simple_compose_01k1zkk4bef1mvfrbhh5t544kx.png?alt=media&token=a0411d0a-64a6-4c42-9efa-395700e0c6a9",
    "aiHint": "Michel de Montaigne",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "France"
  },
  {
    "id": "giordano-bruno",
    "name": "Giordano Bruno",
    "description": "An Italian Dominican friar, philosopher, mathematician, poet, and cosmological theorist. He is known for his cosmological theories, which conceptually extended the then-novel Copernican model.",
    "description_pt": "Um frade dominicano italiano, filósofo, matemático, poeta e teórico cosmológico. Ele é conhecido por suas teorias cosmológicas, que estenderam conceitualmente o então novo modelo copernicano.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FGiordano%20Bruno%20Portrait_simple_compose_01k22da7r6f8ea2ftxh7znza38.png?alt=media&token=379e51a3-800e-4745-9174-c93b97080dac",
    "aiHint": "Giordano Bruno",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Italy"
  },
  {
    "id": "luis-de-camoes",
    "name": "Luís de Camões",
    "description": "Portugal's and the Portuguese language's greatest poet. His mastery of verse has been compared to that of Shakespeare, Vondel, Homer, Virgil and Dante.",
    "description_pt": "O maior poeta de Portugal e da língua portuguesa. Sua maestria no verso foi comparada à de Shakespeare, Vondel, Homero, Virgílio e Dante.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FLu%C3%ADs%20de%20Cam%C3%B5es%20Portrait_simple_compose_01k1zkj47pe3kbp3nbve23e244.png?alt=media&token=4dcf57d6-4fa6-44dd-a154-42e7600dda2a",
    "aiHint": "Luis de Camoes",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Portugal"
  },
  {
    "id": "francesco-guicciardini",
    "name": "Francesco Guicciardini",
    "description": "An Italian historian and statesman. A friend and critic of Machiavelli, he is considered one of the major political writers of the Italian Renaissance.",
    "description_pt": "Um historiador e estadista italiano. Amigo e crítico de Maquiavel, é considerado um dos maiores escritores políticos do Renascimento italiano.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FFrancesco%20Guicciardini%20Portrait_simple_compose_01k1xs22steh3rsm48nh2gxc98.png?alt=media&token=3e251c6c-8646-4f7a-9508-7607f2c23598",
    "aiHint": "Francesco Guicciardini",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "History",
    "field_pt": "História",
    "country": "Italy"
  },
  {
    "id": "jean-bodin",
    "name": "Jean Bodin",
    "description": "A French jurist and political philosopher, member of the Parlement of Paris and professor of law in Toulouse. He is best known for his theory of sovereignty.",
    "description_pt": "Um jurista e filósofo político francês, membro do Parlamento de Paris e professor de direito em Toulouse. Ele é mais conhecido por sua teoria da soberania.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FJean%20Bodin%20Portrait_simple_compose_01k1xshdhwf2a8ke0bkawmyccb.png?alt=media&token=5267f5dd-b254-4ef3-bbc9-d8a14af59799",
    "aiHint": "Jean Bodin",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "History",
    "field_pt": "História",
    "country": "France"
  },
  {
    "id": "julius-caesar",
    "name": "Júlio César",
    "description": "A Roman general and statesman who played a critical role in the events that led to the demise of the Roman Republic and the rise of the Roman Empire.",
    "description_pt": "Um general e estadista romano que desempenhou um papel crítico nos eventos que levaram ao fim da República Romana e à ascensão do Império Romano.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FJulius%20Caesar%20Portrait_simple_compose_01k6k42fgtf1n9zp3tthy8c14s.png?alt=media&token=091fdfa0-e8e5-4e6c-9b33-86cd8fa2bf3f",
    "aiHint": "Julius Caesar",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Rome"
  },
  {
    "id": "pericles",
    "name": "Péricles",
    "description": "A prominent and influential Greek statesman, orator and general of Athens during its golden age – specifically the time between the Persian and Peloponnesian wars.",
    "description_pt": "Um proeminente e influente estadista, orador e general grego de Atenas durante sua idade de ouro - especificamente o tempo entre as guerras Persas e do Peloponeso.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FPericles%20Portrait_simple_compose_01k1x0813jehzs2ckc6x7atcr9.png?alt=media&token=7ee4e6b2-14c4-4eb9-8761-f1962c9a3e8e",
    "aiHint": "Pericles athens",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Athens"
  },
  {
    "id": "archimedes",
    "name": "Arquimedes",
    "description": "A Greek mathematician, physicist, engineer, inventor, and astronomer. He is regarded as one of the leading scientists in classical antiquity.",
    "description_pt": "Um matemático, físico, engenheiro, inventor e astrônomo grego. Ele é considerado um dos principais cientistas da antiguidade clássica.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FArchimedes%20Renaissance%20Portrait_simple_compose_01k1tqnmkrf1fv4bfq6n52x9e4.png?alt=media&token=99819f33-179e-499d-90e5-bea064296b0a",
    "aiHint": "Archimedes scientist",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Greece"
  },
  {
    "id": "imhotep",
    "name": "Imhotep",
    "description": "An Egyptian chancellor to the pharaoh Djoser, probable architect of the step pyramid, and high priest of the sun god Ra at Heliopolis.",
    "description_pt": "Um chanceler egípcio do faraó Djoser, provável arquiteto da pirâmide de degraus e sumo sacerdote do deus sol Rá em Heliópolis.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FImhotep%20in%20Renaissance%20Style_simple_compose_01k1trn04wewa8q5gjpf12rjpy.png?alt=media&token=06fa6448-926d-4a55-b52a-dff5a4701275",
    "aiHint": "Imhotep egypt",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Egypt"
  },
  {
    "id": "hippocrates",
    "name": "Hipócrates",
    "description": "A Greek physician of the Age of Pericles, who is considered one of the most outstanding figures in the history of medicine. He is often referred to as the 'Father of Medicine'.",
    "description_pt": "Um médico grego da Idade de Péricles, considerado uma das figuras mais proeminentes da história da medicina. Ele é frequentemente referido como o 'Pai da Medicina'.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FHippocrates%20Portrait_simple_compose_01k1trbr0hfsr81jnka2h3erhr.png?alt=media&token=e9474045-9b62-4ec8-9d8d-9f4278e96cf1",
    "aiHint": "Hippocrates medicine",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Greece"
  },
  {
    "id": "ptolemy",
    "name": "Ptolomeu",
    "description": "A Greco-Roman mathematician, astronomer, geographer and astrologer. He lived in the city of Alexandria in the Roman province of Egypt, under Roman rule.",
    "description_pt": "Um matemático, astrônomo, geógrafo e astrólogo greco-romano. Ele viveu na cidade de Alexandria, na província romana do Egito, sob o domínio romano.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FPtolemy%20Renaissance%20Portrait_simple_compose_01k1x00fz7fa382xxmsxagdrxg.png?alt=media&token=31e6d192-14a4-4409-8d00-e9d5547574e1",
    "aiHint": "Ptolemy astronomer",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Egypt"
  },
  {
    "id": "socrates",
    "name": "Sócrates",
    "description": "A classical Greek (Athenian) philosopher credited as one of the founders of Western philosophy, and as being the first moral philosopher of the Western ethical tradition of thought.",
    "description_pt": "Um filósofo grego clássico (ateniense) creditado como um dos fundadores da filosofia ocidental e como sendo o primeiro filósofo moral da tradição ética de pensamento ocidental.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FSocrates%20Portrait_simple_compose_01k1x2btqaepht4t65pk640ysz.png?alt=media&token=8ffb43b7-f244-43cd-8737-21b7cc606217",
    "aiHint": "Socrates philosopher",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Greece"
  },
  {
    "id": "laozi",
    "name": "Laozi",
    "description": "An ancient Chinese philosopher and writer. He is the reputed author of the Tao Te Ching, the founder of philosophical Taoism, and a deity in religious Taoism and traditional Chinese religions.",
    "description_pt": "Um antigo filósofo e escritor chinês. Ele é o autor reputado do Tao Te Ching, o fundador do taoísmo filosófico e uma divindade no taoísmo religioso e nas religiões tradicionais chinesas.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FLaozi%20Portrait_simple_compose_01k1v0jqa1e92rgndfm1rpyybe.png?alt=media&token=806fe7ff-095c-4efb-ab0d-1687c96143be",
    "aiHint": "Laozi philosopher",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "China"
  },
  {
    "id": "homer",
    "name": "Homero",
    "description": "The presumed author of the Iliad and the Odyssey, two epic poems that are the central works of ancient Greek literature.",
    "description_pt": "O presumível autor da Ilíada e da Odisseia, dois poemas épicos que são as obras centrais da literatura grega antiga.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FHomer%20Portrait_simple_compose_01k1trgn75f6v91cajsrfydn7g.png?alt=media&token=49fa358f-ac74-4784-a9e8-f6815610de25",
    "aiHint": "Homer poet",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Greece"
  },
  {
    "id": "virgil",
    "name": "Virgílio",
    "description": "An ancient Roman poet of the Augustan period. He wrote three of the most famous poems in Latin literature: the Eclogues, the Georgics, and the epic Aeneid.",
    "description_pt": "Um antigo poeta romano do período augustano. Ele escreveu três dos poemas mais famosos da literatura latina: as Éclogas, as Geórgicas e a épica Eneida.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FVirgil%20in%20Renaissance%20Style_simple_compose_01k1x8bsc9fjas8tvdc9w1rz5n.png?alt=media&token=51baa42e-af62-40e2-99d6-9e74751d9d8f",
    "aiHint": "Virgil poet",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Rome"
  },
  {
    "id": "herodotus",
    "name": "Heródoto",
    "description": "A Greek writer who invented the field of study known today as 'history'. He was the first writer to perform systematic investigation of historical events.",
    "description_pt": "Um escritor grego que inventou o campo de estudo conhecido hoje como 'história'. Ele foi o primeiro escritor a realizar uma investigação sistemática de eventos históricos.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FHerodotus%20Renaissance%20Portrait_simple_compose_01k1tr3v78eftrewr8f3cz6zxk.png?alt=media&token=28d92434-7a81-4478-a654-00e80435b9a9",
    "aiHint": "Herodotus history",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "History",
    "field_pt": "História",
    "country": "Greece"
  },
  {
    "id": "sima-qian",
    "name": "Sima Qian",
    "description": "A Chinese historian of the early Han dynasty. He is considered the father of Chinese historiography for his Records of the Grand Historian.",
    "description_pt": "Um historiador chinês do início da dinastia Han. Ele é considerado o pai da historiografia chinesa por seus Registros do Grande Historiador.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FSima%20Qian%20Renaissance%20Portrait_simple_compose_01k1x15b2sexd93em8a05qd762.png?alt=media&token=b9b891fc-c375-44c6-b6c1-3e3149c98f79",
    "aiHint": "Sima Qian historian",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "History",
    "field_pt": "História",
    "country": "China"
  },
  {
    "id": "marie-curie",
    "name": "Marie Curie",
    "description": "A Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. She was the first woman to win a Nobel Prize.",
    "description_pt": "Uma física e química polonesa, naturalizada francesa, que conduziu pesquisas pioneiras sobre radioatividade. Foi a primeira mulher a ganhar um Prêmio Nobel.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2F20250803_1447_Marie%20Curie%20Renaissance%20Portrait_simple_compose_01k1rgm5wkew0tsa9d6r90ptnq.png?alt=media&token=254e0601-6718-4fa2-ac5f-76c8d351c956",
    "aiHint": "Marie Curie",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Poland/France"
  },
  {
    "id": "william-shakespeare",
    "name": "William Shakespeare",
    "description": "An English playwright, poet, and actor, widely regarded as the greatest writer in the English language and the world's pre-eminent dramatist.",
    "description_pt": "Um dramaturgo, poeta e ator inglês, amplamente considerado o maior escritor da língua inglesa e o mais importante dramaturgo do mundo.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2F20250803_1451_Shakespeare%20in%20Renaissance%20Portrait_simple_compose_01k1rgsefrej2t9yqxgtbxx4mp.png?alt=media&token=9bf746e4-5212-467f-9b87-a7a103ee9a01",
    "aiHint": "Shakespeare writer",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "England"
  },
  {
    "id": "albert-einstein",
    "name": "Albert Einstein",
    "description": "A German-born theoretical physicist who developed the theory of relativity, one of the two pillars of modern physics. His work is also known for its influence on the philosophy of science.",
    "description_pt": "Um físico teórico nascido na Alemanha que desenvolveu a teoria da relatividade, um dos dois pilares da física moderna. Seu trabalho também é conhecido por sua influência na filosofia da ciência.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2F20250803_1510_Renaissance%20Einstein%20Portrait_simple_compose_01k1rhyz8fepbafrps88cqkyem_compressed.png?alt=media&token=7c6e4b1b-e177-4203-9b85-a6c4dff06685",
    "aiHint": "Albert Einstein scientist",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Germany/USA"
  },
  {
    "id": "isaac-newton",
    "name": "Isaac Newton",
    "description": "An English mathematician, physicist, and astronomer who was a pivotal figure in the scientific revolution. His formulation of the laws of motion and universal gravitation laid the groundwork for classical mechanics.",
    "description_pt": "Um matemático, físico e astrônomo inglês que foi uma figura central na revolução científica. Sua formulação das leis do movimento e da gravitação universal estabeleceu as bases da mecânica clássica.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FNewton%20Portrait_simple_compose_01k36sncwvf7va409q89z9rnvq%20(1).png?alt=media&token=d41d79e0-1062-45a4-a88b-2d430ad9098d",
    "aiHint": "Isaac Newton scientist",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "England"
  },
  {
    "id": "plato",
    "name": "Platão",
    "description": "A Greek philosopher who was a foundational figure in Western thought, founded the Academy in Athens. His dialogues, including 'The Republic,' explored justice, beauty, and equality, shaping political theory and metaphysics.",
    "description_pt": "Um filósofo grego que foi uma figura fundamental no pensamento ocidental e fundou a Academia em Atenas. Seus diálogos, incluindo 'A República', exploraram a justiça, a beleza e a igualdade, moldando a teoria política e a metafísica.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FPlato%20Portrait_simple_compose_01k36t13hfegvtcpqa8g10dpxa_1.png?alt=media&token=16358e4b-9b7f-42ba-a05a-6c6765bc6cca",
    "aiHint": "Plato philosopher",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Greece"
  },
  {
    "id": "aristotle",
    "name": "Aristóteles",
    "description": "A Greek philosopher and polymath who was a student of Plato. His writings cover a vast range of subjects, from logic and ethics to biology and politics, and became the foundation of Western philosophy.",
    "description_pt": "Um filósofo e polímata grego que foi aluno de Platão. Seus escritos abrangem uma vasta gama de assuntos, da lógica e ética à biologia e política, e se tornaram a base da filosofia ocidental.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FAristotle%20Portrait_simple_compose_01k36t0ff8ewyttg4n9k3c17r5.png?alt=media&token=2cf4e75c-1bee-44e5-b7df-ed6acd06f21c",
    "aiHint": "Aristotle philosopher",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Greece"
  },
  {
    "id": "mary-wollstonecraft",
    "name": "Mary Wollstonecraft",
    "description": "An English writer and a passionate advocate of women's rights and educational reform. Her work, 'A Vindication of the Rights of Woman,' is a foundational text of modern feminism.",
    "description_pt": "Uma escritora inglesa e uma defensora apaixonada dos direitos das mulheres e da reforma educacional. Sua obra, 'Uma Reivindicação dos Direitos da Mulher', é um texto fundamental do feminismo moderno.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMary%20Wollstonecraft%20Portrait_simple_compose_01k36tq9baedy8tsgajf36fc27.png?alt=media&token=d1b54706-ddb5-4f9a-b0b6-1c1678ce7cf5",
    "aiHint": "Mary Wollstonecraft writer",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "England"
  },
  {
    "id": "martin-luther-king-jr",
    "name": "Martin Luther King Jr.",
    "description": "An American Baptist minister and activist who became the most visible spokesperson and leader in the Civil Rights Movement. He is best known for advancing civil rights through nonviolence and civil disobedience.",
    "description_pt": "Um pastor batista e ativista americano que se tornou o porta-voz e líder mais visível no Movimento dos Direitos Civis. Ele é mais conhecido por promover os direitos civis através da não-violência e da desobediência civil.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMLK%20Portrait_simple_compose_01k36tqr2gf7rbtnwccqeckynn.png?alt=media&token=50a28a2c-c354-4bb0-841e-a460e8a9b8a5",
    "aiHint": "Martin Luther King",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Politics",
    "field_pt": "Política",
    "country": "USA"
  },
  {
    "id": "gavrilo-princip",
    "name": "Gavrilo Princip",
    "description": "A Bosnian Serb member of Young Bosnia who assassinated Archduke Franz Ferdinand of Austria in Sarajevo on 28 June 1914, sparking the outbreak of World War I.",
    "description_pt": "Um sérvio-bósnio membro da Jovem Bósnia que assassinou o arquiduque Francisco Ferdinando da Áustria em Sarajevo em 28 de junho de 1914, desencadeando o início da Primeira Guerra Mundial.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FGavrilo%20Princip%20Portrait_simple_compose_01k39amw9rfbz8kfdqtr839p3h.png?alt=media&token=425aa8e6-c7d8-43b1-a593-ecd17b390358",
    "aiHint": "Gavrilo Princip",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "History",
    "field_pt": "História",
    "country": "Bosnia / Serbia"
  },
  {
    "id": "franz-ferdinand",
    "name": "Franz Ferdinand",
    "description": "Archduke of Austria-Este, Austro-Hungarian and Royal Prince of Hungary and of Bohemia, and from 1896 until his death, heir presumptive to the Austro-Hungarian throne. His assassination in Sarajevo is considered the most immediate cause of World War I.",
    "description_pt": "Arquiduque da Áustria-Este, Príncipe Austro-Húngaro e Real da Hungria e da Boêmia e, de 1896 até sua morte, herdeiro presuntivo do trono Austro-Húngaro. Seu assassinato em Sarajevo é considerado a causa mais imediata da Primeira Guerra Mundial.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FFranz%20Ferdinand%20Portrait_simple_compose_01k3r7fr47e86rxtmv9pxegfx8.png?alt=media&token=e7ec2efb-c776-4514-9852-d9dab3828cf3",
    "aiHint": "Franz Ferdinand",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Austria-Hungary"
  },
  {
    "id": "woodrow-wilson",
    "name": "Woodrow Wilson",
    "description": "The 28th president of the United States, serving from 1913 to 1921. A member of the Democratic Party, Wilson oversaw the passage of progressive legislative policies and led the United States during World War I.",
    "description_pt": "O 28º presidente dos Estados Unidos, servindo de 1913 a 1921. Membro do Partido Democrata, Wilson supervisionou a aprovação de políticas legislativas progressistas e liderou os Estados Unidos durante a Primeira Guerra Mundial.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FWoodrow%20Wilson%20Portrait_simple_compose_01k3r7pvyhe0wt5ph983t0sdxy.png?alt=media&token=b3ef72c0-0464-428e-a5f0-cef5a0d96cb4",
    "aiHint": "Woodrow Wilson",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Politics",
    "field_pt": "Política",
    "country": "USA"
  },
  {
    "id": "franklin-roosevelt",
    "name": "Franklin D. Roosevelt",
    "description": "The 32nd U.S. President, who led the country through the Great Depression and World War II. He is known for his New Deal domestic agenda and his wartime leadership.",
    "description_pt": "O 32º Presidente dos EUA, que liderou o país durante a Grande Depressão e a Segunda Guerra Mundial. É conhecido por sua agenda doméstica do New Deal e por sua liderança em tempos de guerra.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FFDR_simple_compose_01k393aptyfjsrak2nyc6q5t4w.png?alt=media&token=5f957bcc-b89c-436c-851c-6e8711d8b103",
    "aiHint": "Franklin Roosevelt",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Politics",
    "field_pt": "Política",
    "country": "USA"
  },
  {
    "id": "joseph-stalin",
    "name": "Joseph Stalin",
    "description": "The leader of the Soviet Union from the 1920s until his death in 1953. He played a crucial role in the defeat of Nazi Germany in World War II but was also responsible for the deaths of millions.",
    "description_pt": "O líder da União Soviética desde a década de 1920 até sua morte em 1953. Ele desempenhou um papel crucial na derrota da Alemanha Nazista na Segunda Guerra Mundial, mas também foi responsável pela morte de milhões.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FStalin%20Military%20Portrait_simple_compose_01k3r7ngh4fztt5p3er46g7tsz.png?alt=media&token=af987aed-80f4-4c83-a785-22a1d6ee1c38",
    "aiHint": "Joseph Stalin",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Soviet Union"
  },
  {
    "id": "charles_de_gaulle",
    "name": "Charles de Gaulle",
    "description": "A French army officer and statesman who led Free France against Nazi Germany in World War II and chaired the Provisional Government of the French Republic from 1944 to 1946 in order to re-establish democracy in France.",
    "description_pt": "Um oficial do exército francês e estadista que liderou a França Livre contra a Alemanha Nazista na Segunda Guerra Mundial e presidiu o Governo Provisório da República Francesa de 1944 a 1946 para restabelecer a democracia na França.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FDe%20Gaulle%20Portrait_simple_compose_01k393e0wpf9zbq0s3jmj668j4.png?alt=media&token=ef983db9-99f1-49b9-bb65-f61e77543739",
    "aiHint": "Charles de Gaulle",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Politics",
    "field_pt": "Política",
    "country": "France"
  },
  {
    "id": "dom_pedro_i",
    "name": "Dom Pedro I",
    "description": "Founder and first ruler of the Empire of Brazil, he reigned as 'Emperor of Brazil' from 1822 to 1831. He declared Brazil's independence from Portugal.",
    "description_pt": "Fundador e primeiro governante do Império do Brasil, reinou como 'Imperador do Brasil' de 1822 a 1831. Ele declarou a independência do Brasil de Portugal.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FDom%20Pedro%20I%20Portrait_simple_compose_01k3r7tc21fb1vgvqxn200xz0z.png?alt=media&token=1d5e4190-04a2-49f8-981d-f44e94d101c8",
    "aiHint": "Dom Pedro I Brazil",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Brazil/Portugal"
  },
  {
    "id": "jose_bonifacio",
    "name": "José Bonifácio",
    "description": "A Brazilian statesman, naturalist, professor, and poet, he was a crucial figure in the Brazilian independence, earning the title of 'Patriarch of Independence.'",
    "description_pt": "Estadista, naturalista, professor e poeta brasileiro, foi uma figura crucial na independência do Brasil, recebendo o título de 'Patriarca da Independência'.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FJos%C3%A9%20Bonif%C3%A1cio%20Portrait_simple_compose_01k3r7wjkxepmt8xh09d58av3a.png?alt=media&token=131c9ee9-cce1-41ce-82e9-14733ec2a998",
    "aiHint": "Jose Bonifacio Brazil",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Brazil"
  },
  {
    "id": "maria_leopoldina",
    "name": "Maria Leopoldina",
    "description": "An Archduchess of Austria and the first Empress of Brazil. She played a significant role in the process of Brazil's independence.",
    "description_pt": "Arquiduquesa da Áustria e primeira Imperatriz do Brasil. Ela desempenhou um papel significativo no processo de independência do Brasil.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMaria%20Leopoldina%20Portrait_simple_compose_01k3r80j87e9ab5xr8zjpfvdwj.png?alt=media&token=9e7d87da-0750-406a-a226-e3ebefe405ec",
    "aiHint": "Maria Leopoldina Brazil",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Austria/Brazil"
  },
  {
    "id": "joao_vi",
    "name": "Dom João VI",
    "description": "King of the United Kingdom of Portugal, Brazil and the Algarves from 1816 to 1825. His court's move to Brazil was a pivotal event that paved the way for independence.",
    "description_pt": "Rei do Reino Unido de Portugal, Brasil e Algarves de 1816 a 1825. A transferência de sua corte para o Brasil foi um evento crucial que abriu caminho para a independência.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FDom%20Jo%C3%A3o%20VI%20Portrait_simple_compose_01k3r7rx5qf3da42461c2k5mxq.png?alt=media&token=0fc848a4-820e-4678-a210-3c180c58ac80",
    "aiHint": "Joao VI Portugal",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Portugal/Brazil"
  },
  {
    "id": "louis-xvi",
    "name": "Louis XVI",
    "description": "The last King of France before the fall of the monarchy during the French Revolution. His reign was marked by attempts at reform that were ultimately overwhelmed by social and economic turmoil.",
    "description_pt": "O último Rei da França antes da queda da monarquia durante a Revolução Francesa. Seu reinado foi marcado por tentativas de reforma que foram finalmente superadas pela turbulência social e econômica.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FLouis%20XVI%20Portrait_simple_compose_01k3r7x9yyf11vechy3v73qkep.png?alt=media&token=7037c378-1d5b-4b10-98b4-8fd12bedfbb0",
    "aiHint": "Louis XVI France",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "France"
  },
  {
    "id": "marie-antoinette",
    "name": "Marie Antoinette",
    "description": "The last Queen of France before the French Revolution. She became a symbol of the excesses of the monarchy, which led to her execution.",
    "description_pt": "A última Rainha da França antes da Revolução Francesa. Ela se tornou um símbolo dos excessos da monarquia, o que levou à sua execução.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMarie%20Antoinette%20Portrait_simple_compose_01k3r81s5vec7rn6q64kp37bq3.png?alt=media&token=8f9dc6d6-8965-4943-90a9-ef36776680fe",
    "aiHint": "Marie Antoinette France",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Austria/France"
  },
  {
    "id": "robespierre",
    "name": "Robespierre",
    "description": "A French lawyer and statesman who was one of the best-known and most influential figures of the French Revolution. He was a key figure during the Reign of Terror.",
    "description_pt": "Um advogado e estadista francês que foi uma das figuras mais conhecidas e influentes da Revolução Francesa. Ele foi uma figura chave durante o Período do Terror.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FRobespierre's%20Intense%20Gaze_simple_compose_01k3r89zfde3ds7k3qe87g7wnz.png?alt=media&token=5c74d637-9994-4a78-b8f1-17713dc65838",
    "aiHint": "Robespierre France",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "France"
  },
  {
    "id": "napoleon-bonaparte",
    "name": "Napoleon Bonaparte",
    "description": "A French statesman and military leader who rose to prominence during the French Revolution and led several successful campaigns during the Revolutionary Wars. He was Emperor of the French from 1804 until 1814 and again briefly in 1815.",
    "description_pt": "Um estadista e líder militar francês que ascendeu à proeminência durante a Revolução Francesa e liderou várias campanhas bem-sucedidas durante as Guerras Revolucionárias. Ele foi Imperador dos Franceses de 1804 a 1814 e novamente por um breve período em 1815.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FNapoleon's%20Regal%20Portrait_simple_compose_01k3r89mwyesx8tdzg999h24vw.png?alt=media&token=c94bc588-7f9b-4de7-8701-20f9188876a7",
    "aiHint": "Napoleon Bonaparte",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "France"
  },
  {
    "id": "jesus_cristo",
    "name": "Jesus Cristo",
    "description": "The central figure of Christianity, believed by Christians to be the Son of God and the Messiah prophesied in the Old Testament.",
    "description_pt": "A figura central do Cristianismo, acreditado pelos cristãos como o Filho de Deus e o Messias profetizado no Antigo Testamento.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FJesus%20Portrait_simple_compose_01k6jz99e2ff1aqvhdrc8c029q.png?alt=media&token=616a66f8-0e30-4bba-96c5-03cb97cbb319",
    "aiHint": "Jesus Christ",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "Middle East",
    "religion": "christianity"
  },
  {
    "id": "martinho_lutero",
    "name": "Martinho Lutero",
    "description": "A German professor of theology, composer, priest, monk, and a seminal figure in the Protestant Reformation. He is best known for his Ninety-five Theses.",
    "description_pt": "Um professor alemão de teologia, compositor, padre, monge e uma figura seminal na Reforma Protestante. Ele é mais conhecido por suas Noventa e cinco Teses.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMartin%20Luther%20Portrait_simple_compose_01k6k5g2nvfwz9zwwaf510y6ph.png?alt=media&token=8130d350-22e5-47c5-93e7-26d12ec74a1f",
    "aiHint": "Martin Luther",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "Germany",
    "religion": "christianity"
  },
  {
    "id": "maome",
    "name": "Maomé",
    "description": "The founder of Islam and proclaimed by Muslims as a prophet of God. He is viewed as the final prophet of God in most mainstream branches of Islam.",
    "description_pt": "O fundador do Islã e proclamado pelos muçulmanos como um profeta de Deus. Ele é visto como o profeta final de Deus na maioria dos ramos principais do Islã.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/religions-portraits%2Fmuhammad.png?alt=media&token=a0b8c7d6-5e4f-4a9b-8c7d-6f5a4b3c2d1e",
    "aiHint": "Prophet Muhammad",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "Arabian Peninsula",
    "religion": "islamism"
  },
  {
    "id": "buda",
    "name": "Buda (Siddhartha Gautama)",
    "description": "A philosopher, mendicant, meditator, spiritual teacher, and religious leader who lived in Ancient India. He is revered as the founder of the world religion of Buddhism.",
    "description_pt": "Um filósofo, mendicante, meditador, professor espiritual e líder religioso que viveu na Índia Antiga. Ele é reverenciado como o fundador da religião mundial do Budismo.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FBuddha%20Portrait_simple_compose_01k6jyy6rwfdysq55fzkqcc5r5.png?alt=media&token=8e770e76-3f36-462f-8cce-7ee89bb5b071",
    "aiHint": "Buddha Gautama",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "India",
    "religion": "buddhism"
  },
  {
    "id": "nagarjuna",
    "name": "Nagarjuna",
    "description": "An Indian Mahāyāna Buddhist thinker, scholar-saint and philosopher. He is widely considered one of the most important Buddhist philosophers.",
    "description_pt": "Um pensador, estudioso-santo e filósofo budista Mahāyāna indiano. Ele é amplamente considerado um dos mais importantes filósofos budistas.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FNagarjuna's%20Contemplative%20Portrait_simple_compose_01k6k5ry4qer0spa6b7j0tan7d.png?alt=media&token=7cecddb1-dab8-4eb0-aec7-7bc63cf9f97e",
    "aiHint": "Nagarjuna philosopher",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "India",
    "religion": "buddhism"
  },
  {
    "id": "dalai_lama",
    "name": "Dalai Lama (14th)",
    "description": "The current Dalai Lama, Tenzin Gyatso, is the spiritual leader of the Tibetan people. He is a Nobel Peace Prize laureate and a global figure of peace and compassion.",
    "description_pt": "O atual Dalai Lama, Tenzin Gyatso, é o líder espiritual do povo tibetano. Ele é um laureado com o Prêmio Nobel da Paz e uma figura global de paz e compaixão.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FDalai%20Lama%20Renaissance%20Portrait_simple_compose_01k6jyyk6wfk3911ww95ff96bq.png?alt=media&token=eacd4213-c819-42f1-b446-caddb221e018",
    "aiHint": "Dalai Lama",
    "era": "Contemporary",
    "era_pt": "Contemporânea",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "Tibet",
    "religion": "buddhism"
  },
  {
    "id": "abraham",
    "name": "Abraão",
    "description": "The common patriarch of the Abrahamic religions, including Judaism, Christianity, and Islam. He is a central figure known for his covenant with God.",
    "description_pt": "O patriarca comum das religiões abraâmicas, incluindo o Judaísmo, Cristianismo e Islamismo. Ele é uma figura central conhecida por sua aliança com Deus.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FAbraham%20Portrait_simple_compose_01k6jymvt1ft3s6dtyygyngpvr.png?alt=media&token=3a5fc1bd-df52-4b90-92b0-bcc3a2d9fdbf",
    "aiHint": "Abraham patriarch",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "Middle East",
    "religion": "judaism"
  },
  {
    "id": "moses",
    "name": "Moisés",
    "description": "A prophet in the Abrahamic religions. According to the Hebrew Bible, he was a former Egyptian prince who led the Israelites out of Egypt and across the Red Sea, after which they wandered in the desert for 40 years.",
    "description_pt": "Um profeta nas religiões abraâmicas. De acordo com a Bíblia Hebraica, ele foi um ex-príncipe egípcio que liderou os israelitas para fora do Egito e através do Mar Vermelho, após o que eles vagaram no deserto por 40 anos.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FMoses%20with%20Stone%20Tablets_simple_compose_01k6k5rpzgf889ncdkqd6g9meb.png?alt=media&token=0d74497d-5a54-4498-b32d-ef1ef4c5e7d8",
    "aiHint": "Moses prophet",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "Middle East",
    "religion": "judaism"
  },
  {
    "id": "king_david",
    "name": "Rei Davi",
    "description": "A king of Israel and Judah. In the biblical narrative, David is a young shepherd who gains fame first as a musician and later by defeating the giant Goliath. He is regarded as a righteous and effective king in battle and civil administration.",
    "description_pt": "Um rei de Israel e Judá. Na narrativa bíblica, Davi é um jovem pastor que ganha fama primeiro como músico e depois ao derrotar o gigante Golias. Ele é considerado um rei justo e eficaz na batalha e na administração civil.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FKing%20David%20Portrait_simple_compose_01k6k67a9hezprr5wx43v7jrkn.png?alt=media&token=61602efb-21cc-4ca9-8041-793965a17858",
    "aiHint": "King David",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "Middle East",
    "religion": "judaism"
  },
  {
    "id": "krishna",
    "name": "Krishna",
    "description": "A major deity in Hinduism. He is worshipped as the eighth avatar of the god Vishnu and also as the supreme God in his own right. He is the god of protection, compassion, tenderness, and love.",
    "description_pt": "Uma importante divindade no Hinduísmo. Ele é adorado como o oitavo avatar do deus Vishnu e também como o Deus supremo por direito próprio. Ele é o deus da proteção, compaixão, ternura e amor.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FKrishna%20Portrait_simple_compose_01k6jz9x6ke62b9md6ykaqtmkm.png?alt=media&token=da793faa-b2dc-423b-90ce-a22f0e53ee1b",
    "aiHint": "Krishna deity",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "India",
    "religion": "hinduism"
  },
  {
    "id": "shiva",
    "name": "Shiva",
    "description": "One of the principal deities of Hinduism. He is the supreme being within Shaivism, one of the major traditions within contemporary Hinduism. Shiva is known as 'The Destroyer' within the Trimurti, the Hindu trinity that includes Brahma and Vishnu.",
    "description_pt": "Uma das principais divindades do Hinduísmo. Ele é o ser supremo no Shaivismo, uma das principais tradições do Hinduísmo contemporâneo. Shiva é conhecido como 'O Destruidor' dentro da Trimurti, a trindade hindu que inclui Brahma e Vishnu.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FShiva%20Portrait_simple_compose_01k6k67s9hf9rvs4aybq1hf32r.png?alt=media&token=824e6baf-ea41-4b26-b6f6-7eaaa07148a5",
    "aiHint": "Shiva deity",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Religion",
    "field_pt": "Religião",
    "country": "India",
    "religion": "hinduism"
  },
  {
    "id": "adi_shankara",
    "name": "Adi Shankara",
    "description": "An Indian philosopher and theologian who consolidated the doctrine of Advaita Vedanta. He is credited with unifying and establishing the main currents of thought in Hinduism.",
    "description_pt": "Um filósofo e teólogo indiano que consolidou a doutrina do Advaita Vedanta. Ele é creditado por unificar e estabelecer as principais correntes de pensamento no Hinduísmo.",
    "image": "https://firebasestorage.googleapis.com/v0/b/time-traveler-talks.firebasestorage.app/o/portraits%2FAdi%20Shankara's%20Portrait_simple_compose_01k6jynk8gfgjb8kqjqx9gnbg5.png?alt=media&token=8446ddf1-9df4-474f-8d2e-cf315e1e48eb",
    "aiHint": "Adi Shankara",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "India",
    "religion": "hinduism"
  }
]
