
export interface Character {
  id: string;
  name: string;
  description: string;
  description_pt: string;
  image: string;
  aiHint: string;
  era: string;
  era_pt: string;
  field: string;
  field_pt: string;
  country: string;
}

const characters: Character[] = [
  {
    id: "cleopatra",
    name: "Cleópatra",
    description: "The last active ruler of the Ptolemaic Kingdom of Egypt. A diplomat, naval commander, linguist, and medical author.",
    description_pt: "A última governante ativa do Reino Ptolomaico do Egito. Uma diplomata, comandante naval, linguista e autora de textos médicos.",
    image: "https://videos.openai.com/vg-assets/assets%2Ftask_01k1rfx2vzfhsaxjevq388rwrq%2F1754242504_img_0.webp?st=2025-08-03T17%3A15%3A51Z&se=2025-08-09T18%3A15%3A51Z&sks=b&skt=2025-08-03T17%3A15%3A51Z&ske=2025-08-09T18%3A15%3A51Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skoid=aa5ddad1-c91a-4f0a-9aca-e20682cc8969&skv=2019-02-02&sv=2018-11-09&sr=b&sp=r&spr=https%2Chttp&sig=h1FoJ%2FU08otcSXSUkEFDhy1sn7FVdD%2BhqmJ8EVGD%2Bps%3D&az=oaivgprodscus",
    aiHint: "egyptian queen",
    era: "Ancient",
    era_pt: "Antiguidade",
    field: "Politics",
    field_pt: "Política",
    country: "Egypt",
  },
  {
    id: "leonardo-da-vinci",
    name: "Leonardo da Vinci",
    description: "An Italian polymath of the High Renaissance who was active as a painter, draughtsman, engineer, scientist, theorist, sculptor, and architect.",
    description_pt: "Um polímata italiano da Alta Renascença que atuou como pintor, desenhista, engenheiro, cientista, teórico, escultor e arquiteto.",
    image: "https://videos.openai.com/vg-assets/assets%2Ftask_01k1rngxgcf3h9dp7nrvb63rvs%2F1754248488_img_0.webp?st=2025-08-03T18%3A09%3A33Z&se=2025-08-09T19%3A09%3A33Z&sks=b&skt=2025-08-03T18%3A09%3A33Z&ske=2025-08-09T19%3A09%3A33Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skoid=aa5ddad1-c91a-4f0a-9aca-e20682cc8969&skv=2019-02-02&sv=2018-11-09&sr=b&sp=r&spr=https%2Chttp&sig=vrBfv2zUihOdotzXccz%2FStH8oJqBjJ3Vs4cScLl8wAc%3D&az=oaivgprodscus",
    aiHint: "renaissance artist",
    era: "Renaissance",
    era_pt: "Renascentista",
    field: "Art & Science",
    field_pt: "Arte & Ciência",
    country: "Italy",
  },
  {
    id: "charles-darwin",
    name: "Charles Darwin",
    description: "An English naturalist, geologist and biologist, widely known for his contributions to the science of evolution.",
    description_pt: "Um naturalista, geólogo e biólogo inglês, amplamente conhecido por suas contribuições para a ciência da evolução.",
    image: "https://videos.openai.com/vg-assets/assets%2Ftask_01k1rgd1szf4vbc4w7ctytvver%2F1754242953_img_1.webp?st=2025-08-03T17%3A50%3A35Z&se=2025-08-09T18%3A50%3A35Z&sks=b&skt=2025-08-03T17%3A50%3A35Z&ske=2025-08-09T18%3A50%3A35Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skoid=aa5ddad1-c91a-4f0a-9aca-e20682cc8969&skv=2019-02-02&sv=2018-11-09&sr=b&sp=r&spr=https%2Chttp&sig=7YBNtfXakWstjGwdecnNTt6E5E7iqq4TqieU7Bp1pVY%3D&az=oaivgprodscus",
    aiHint: "scientist portrait",
    era: "Victorian",
    era_pt: "Vitoriana",
    field: "Science",
    field_pt: "Ciência",
    country: "United Kingdom",
  },
  {
    id: "confucius",
    name: "Confúcio",
    description: "A Chinese philosopher and politician of the Spring and Autumn period who is traditionally considered the paragon of Chinese sages.",
    description_pt: "Um filósofo e político chinês do período das Primaveras e Outonos, tradicionalmente considerado o paradigma dos sábios chineses.",
    image: "https://videos.openai.com/vg-assets/assets%2Ftask_01k1rgg8e6fz6b7mk4534ng96e%2F1754243062_img_0.webp?st=2025-08-03T17%3A50%3A35Z&se=2025-08-09T18%3A50%3A35Z&sks=b&skt=2025-08-03T17%3A50%3A35Z&ske=2025-08-09T18%3A50%3A35Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skoid=aa5ddad1-c91a-4f0a-9aca-e20682cc8969&skv=2019-02-02&sv=2018-11-09&sr=b&sp=r&spr=https%2Chttp&sig=%2BPZHnGAzyRCxfWX8%2FQkS72DFIx4YuLYATI%2BkgFjvTOI%3D&az=oaivgprodscus",
    aiHint: "chinese philosopher",
    era: "Ancient",
    era_pt: "Antiguidade",
    field: "Philosophy",
    field_pt: "Filosofia",
    country: "China",
  },
  {
    id: "marie-curie",
    name: "Marie Curie",
    description: "A Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. The first woman to win a Nobel Prize.",
    description_pt: "Uma física e química polonesa e naturalizada francesa que conduziu pesquisas pioneiras sobre radioatividade. A primeira mulher a ganhar um Prêmio Nobel.",
    image: "https://videos.openai.com/vg-assets/assets%2Ftask_01k1rgm511fkm8v6rrawqj897y%2F1754243252_img_0.webp?st=2025-08-03T17%3A50%3A35Z&se=2025-08-09T18%3A50%3A35Z&sks=b&skt=2025-08-03T17%3A50%3A35Z&ske=2025-08-09T18%3A50%3A35Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skoid=aa5ddad1-c91a-4f0a-9aca-e20682cc8969&skv=2019-02-02&sv=2018-11-09&sr=b&sp=r&spr=https-2Chttp&sig=CvJCK-2Bacw-2FCJ5k1LNrk7EFct78TJPex1RSy984b6Ahg-3D&az=oaivgprodscus",
    aiHint: "female scientist",
    era: "Modern",
    era_pt: "Moderna",
    field: "Science",
    field_pt: "Ciência",
    country: "Poland/France",
  },
  {
    id: "william-shakespeare",
    name: "William Shakespeare",
    description: "An English playwright, poet and actor, widely regarded as the greatest writer in the English language and the world's pre-eminent dramatist.",
    description_pt: "Um dramaturgo, poeta e ator inglês, amplamente considerado o maior escritor da língua inglesa e o mais proeminente dramaturgo do mundo.",
    image: "https://videos.openai.com/vg-assets/assets%2Ftask_01k1rgsd5xendsd6bxbrkn45x8%2F1754243488_img_0.webp?st=2025-08-03T17%3A50%3A35Z&se=2025-08-09T18%3A50%3A35Z&sks=b&skt=2025-08-03T17%3A50%3A35Z&ske=2025-08-09T18%3A50%3A35Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skoid=aa5ddad1-c91a-4f0a-9aca-e20682cc8969&skv=2019-02-02&sv=2018-11-09&sr=b&sp=r&spr=https-2Chttp&sig=9NI0lrLl04fRCPgk2NNCaENxAaOcz9m3yiFAVCyNKtE-3D&az=oaivgprodscus",
    aiHint: "playwright portrait",
    era: "Renaissance",
    era_pt: "Renascentista",
    field: "Literature",
    field_pt: "Literatura",
    country: "United Kingdom",
  },
  {
    id: "albert-einstein",
    name: "Albert Einstein",
    description: "A German-born theoretical physicist who developed the theory of relativity, one of the two pillars of modern physics.",
    description_pt: "Um físico teórico nascido na Alemanha que desenvolveu a teoria da relatividade, um dos dois pilares da física moderna.",
    image: "https://videos.openai.com/vg-assets/assets%2Ftask_01k1rhyyhhem9b3gftdazq288q%2F1754244644_img_0.webp?st=2025-08-03T17%3A50%3A35Z&se=2025-08-09T18%3A50%3A35Z&sks=b&skt=2025-08-03T17%3A50%3A35Z&ske=2025-08-09T18%3A50%3A35Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skoid=aa5ddad1-c91a-4f0a-9aca-e20682cc8969&skv=2019-02-02&sv=2018-11-09&sr=b&sp=r&spr=https-2Chttp&sig=x1zBC-2FD-2FK6dDvIenBUnvNpi3ZhRDuswhJ7q9KizKdCQ-3D&az=oaivgprodscus",
    aiHint: "genius scientist",
    era: "Modern",
    era_pt: "Moderna",
    field: "Science",
    field_pt: "Ciência",
    country: "Germany/USA",
  },
  {
    id: "joan-of-arc",
    name: "Joana d'Arc",
    description: "A peasant girl who, believing she was acting under divine guidance, led the French army in a momentous victory at Orléans that repulsed an English attempt to conquer France during the Hundred Years' War.",
    description_pt: "Uma camponesa que, acreditando estar agindo sob orientação divina, liderou o exército francês em uma vitória memorável em Orléans, que repeliu uma tentativa inglesa de conquistar a França durante a Guerra dos Cem Anos.",
    image: "https://videos.openai.com/vg-assets/assets%2Ftask_01k1rje5nrf74tyeq8gnf1mv6g%2F1754245090_img_1.webp?st=2025-08-03T17%3A50%3A35Z&se=2025-08-09T18%3A50%3A35Z&sks=b&skt=2025-08-03T17%3A50%3A35Z&ske=2025-08-09T18%3A50%3A35Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skoid=aa5ddad1-c91a-4f0a-9aca-e20682cc8969&skv=2019-02-02&sv=2018-11-09&sr=b&sp=r&spr=https%2Chttp&sig=I7vSn3b8teMs1QAjPCpgEwKeWZ2fGa1BFolnPAwDuZY%3D&az=oaivgprodscus",
    aiHint: "female warrior",
    era: "Medieval",
    era_pt: "Medieval",
    field: "History",
    field_pt: "História",
    country: "France",
  },
  {
    id: "charlemagne",
    name: "Carlos Magno",
    description: "King of the Franks and Lombards, and the first Holy Roman Emperor, who united much of Western and Central Europe.",
    description_pt: "Rei dos Francos e Lombardos, e o primeiro Sacro Imperador Romano, que uniu grande parte da Europa Ocidental e Central.",
    image: "https://placehold.co/400x400.png",
    aiHint: "medieval emperor",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Politics",
    field_pt: "Política",
    country: "France",
  },
  {
    id: "saladin",
    name: "Saladino",
    description: "The first sultan of Egypt and Syria and the founder of the Ayyubid dynasty. He led the Muslim military campaign against the Crusader states in the Levant.",
    description_pt: "O primeiro sultão do Egito e da Síria e o fundador da dinastia Aiúbida. Ele liderou a campanha militar muçulmana contra os estados cruzados no Levante.",
    image: "https://placehold.co/400x400.png",
    aiHint: "sultan warrior",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Politics",
    field_pt: "Política",
    country: "Middle East",
  },
  {
    id: "hildegard-of-bingen",
    name: "Hildegarda de Bingen",
    description: "A German Benedictine abbess, writer, composer, philosopher, mystic, visionary, and medical writer and practitioner.",
    description_pt: "Uma abadessa beneditina alemã, escritora, compositora, filósofa, mística, visionária e escritora e praticante de medicina.",
    image: "https://placehold.co/400x400.png",
    aiHint: "german abbess",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Art & Science",
    field_pt: "Arte & Ciência",
    country: "Germany",
  },
  {
    id: "avicenna",
    name: "Avicena / Ibn Sina",
    description: "A Persian polymath who is regarded as one of the most significant physicians, astronomers, thinkers and writers of the Islamic Golden Age.",
    description_pt: "Um polímata persa que é considerado um dos mais significativos médicos, astrônomos, pensadores e escritores da Idade de Ouro Islâmica.",
    image: "https://placehold.co/400x400.png",
    aiHint: "persian polymath",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Art & Science",
    field_pt: "Arte & Ciência",
    country: "Persia",
  },
  {
    id: "roger-bacon",
    name: "Roger Bacon",
    description: "An English philosopher and Franciscan friar who placed considerable emphasis on the study of nature through empiricism.",
    description_pt: "Um filósofo inglês e frade franciscano que deu ênfase considerável ao estudo da natureza através do empirismo.",
    image: "https://placehold.co/400x400.png",
    aiHint: "english philosopher",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Science",
    field_pt: "Ciência",
    country: "England",
  },
  {
    id: "alhazen",
    name: "Alhazen / Ibn al-Haytham",
    description: "An Arab mathematician, astronomer, and physicist of the Islamic Golden Age. Referred to as 'the father of modern optics'.",
    description_pt: "Um matemático, astrônomo e físico árabe da Idade de Ouro Islâmica. Referido como 'o pai da óptica moderna'.",
    image: "https://placehold.co/400x400.png",
    aiHint: "arab scientist",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Science",
    field_pt: "Ciência",
    country: "Persia",
  },
  {
    id: "thomas-aquinas",
    name: "Santo Tomás de Aquino",
    description: "An Italian Dominican friar, philosopher, Catholic priest, and Doctor of the Church. An immensely influential philosopher and theologian.",
    description_pt: "Um frade dominicano italiano, filósofo, padre católico e Doutor da Igreja. Um filósofo e teólogo imensamente influente.",
    image: "https://placehold.co/400x400.png",
    aiHint: "italian philosopher",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Philosophy",
    field_pt: "Filosofia",
    country: "Italy",
  },
  {
    id: "maimonides",
    name: "Maimônides",
    description: "A medieval Sephardic Jewish philosopher who became one of the most prolific and influential Torah scholars of the Middle Ages.",
    description_pt: "Um filósofo judeu sefardita medieval que se tornou um dos mais prolíficos e influentes estudiosos da Torá da Idade Média.",
    image: "https://placehold.co/400x400.png",
    aiHint: "jewish philosopher",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Philosophy",
    field_pt: "Filosofia",
    country: "Spain/Jewish",
  },
  {
    id: "dante-alighieri",
    name: "Dante Alighieri",
    description: "An Italian poet, writer and philosopher. His Divine Comedy is widely considered the most important poem of the Middle Ages.",
    description_pt: "Um poeta, escritor e filósofo italiano. Sua Divina Comédia é amplamente considerada o poema mais importante da Idade Média.",
    image: "https://placehold.co/400x400.png",
    aiHint: "italian poet",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Literature",
    field_pt: "Literatura",
    country: "Italy",
  },
  {
    id: "chretien-de-troyes",
    name: "Chrétien de Troyes",
    description: "A French poet and trouvère known for his work on Arthurian subjects, and for originating the character of Lancelot.",
    description_pt: "Um poeta e trovador francês conhecido por seu trabalho sobre temas arturianos e por originar o personagem de Lancelot.",
    image: "https://placehold.co/400x400.png",
    aiHint: "french poet",
    era: "Medieval",
    era_pt: "Medieval",
    field: "Literature",
    field_pt: "Literatura",
    country: "France",
  },
  {
    id: "bede",
    name: "Beda, o Venerável",
    description: "An English Benedictine monk at the monastery of St. Peter. His 'Ecclesiastical History of the English People' gained him the title 'The Father of English History'.",
    description_pt: "Um monge beneditino inglês no mosteiro de São Pedro. Sua 'História Eclesiástica do Povo Inglês' lhe rendeu o título de 'O Pai da História Inglesa'.",
    image: "https://placehold.co/400x400.png",
    aiHint: "english monk",
    era: "Medieval",
    era_pt: "Medieval",
    field: "History",
    field_pt: "História",
    country: "England",
  },
  {
    id: "ibn-khaldun",
    name: "Ibn Khaldun",
    description: "An Arab sociologist, philosopher, and historian who has been described as the pre-eminent founder of the protodisciplines that would become historiography, sociology, and economics.",
    description_pt: "Um sociólogo, filósofo e historiador árabe que foi descrito como o fundador preeminente das protodisciplinas que se tornariam historiografia, sociologia e economia.",
    image: "https://placehold.co/400x400.png",
    aiHint: "arab historian",
    era: "Medieval",
    era_pt: "Medieval",
    field: "History",
    field_pt: "História",
    country: "Tunisia",
  },
];

export function getCharacters(): Character[] {
  return characters;
}

export function getCharacterById(id: string): Character | undefined {
  return characters.find((character) => character.id === id);
}
