
import type { Character } from "./characters";

export const charactersData: Character[] = [
  {
    "id": "cleopatra",
    "name": "Cleópatra",
    "description": "The last active ruler of the Ptolemaic Kingdom of Egypt. A skilled diplomat and linguist, she navigated complex Roman politics to protect her empire.",
    "description_pt": "A última governante ativa do Reino Ptolomaico do Egito. Uma diplomata e linguista habilidosa, ela navegou pela complexa política romana para proteger seu império.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "cleopatra egypt",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Egypt"
  },
  {
    "id": "leonardo-da-vinci",
    "name": "Leonardo da Vinci",
    "description": "An Italian polymath of the High Renaissance who is widely considered one of the most diversely talented individuals ever to have lived.",
    "description_pt": "Um polímata italiano da Alta Renascença que é amplamente considerado um dos indivíduos mais talentosos e diversificados que já existiram.",
    "image": "https://videos.openai.com/vg-assets/assets%2Ftask_01k1rngxgcf3h9dp7nrvb63rvs%2F1754248488_img_0.webp?st=2025-08-03T18%3A09%3A33Z&se=2025-08-09T19%3A09%3A33Z&sks=b&skt=2025-08-03T18%3A09%3A33Z&ske=2025-08-09T19%3A09%3A33Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skoid=aa5ddad1-c91a-4f0a-9aca-e20682cc8969&skv=2019-02-02&sv=2018-11-09&sr=b&sp=r&spr=https%2Chttp&sig=vrBfv2zUihOdotzXccz%2FStH8oJqBjJ3Vs4cScLl8wAc%3D&az=oaivgprodscus",
    "aiHint": "da vinci",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Italy"
  },
  {
    "id": "confucius",
    "name": "Confúcio",
    "description": "A Chinese philosopher and politician of the Spring and Autumn period who is traditionally considered the paragon of Chinese sages.",
    "description_pt": "Um filósofo e político chinês do período da Primavera e Outono que é tradicionalmente considerado o modelo dos sábios chineses.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "confucius philosopher",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "China"
  },
  {
    "id": "joan-of-arc",
    "name": "Joana d'Arc",
    "description": "A peasant girl who, believing she was acting under divine guidance, led the French army in a momentous victory at Orléans in 1429.",
    "description_pt": "Uma camponesa que, acreditando estar agindo sob orientação divina, liderou o exército francês em uma vitória momentosa em Orléans em 1429.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "joan arc",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "History",
    "field_pt": "História",
    "country": "France"
  },
  {
    "id": "charlemagne",
    "name": "Carlos Magno",
    "description": "King of the Franks who united most of Western Europe during the Early Middle Ages and laid the foundations for modern France and Germany.",
    "description_pt": "Rei dos Francos que uniu a maior parte da Europa Ocidental durante a Alta Idade Média e lançou as bases para a França e Alemanha modernas.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Charlemagne king",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Politics",
    "field_pt": "Política",
    "country": "France"
  },
  {
    "id": "saladin",
    "name": "Saladino",
    "description": "A Sunni Muslim Kurd who became the first sultan of both Egypt and Syria, and founded the Ayyubid dynasty. He led the Muslim military campaign against the Crusader states in the Levant.",
    "description_pt": "Um curdo muçulmano sunita que se tornou o primeiro sultão do Egito e da Síria e fundou a dinastia Aiúbida. Ele liderou a campanha militar muçulmana contra os estados cruzados no Levante.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Saladin sultan",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Middle East"
  },
  {
    "id": "hildegard-of-bingen",
    "name": "Hildegarda de Bingen",
    "description": "A German Benedictine abbess, writer, composer, philosopher, mystic, visionary, and medical writer and practitioner during the High Middle Ages.",
    "description_pt": "Uma abadessa beneditina alemã, escritora, compositora, filósofa, mística, visionária e escritora e praticante de medicina durante a Alta Idade Média.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Hildegard Bingen",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Germany"
  },
  {
    "id": "avicenna",
    "name": "Avicena / Ibn Sina",
    "description": "A Persian polymath who is regarded as one of the most significant physicians, astronomers, thinkers and writers of the Islamic Golden Age.",
    "description_pt": "Um polímata persa que é considerado um dos mais significativos médicos, astrônomos, pensadores e escritores da Idade de Ouro Islâmica.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Avicenna polymath",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Persia"
  },
  {
    "id": "roger-bacon",
    "name": "Roger Bacon",
    "description": "An English philosopher and Franciscan friar who placed considerable emphasis on the study of nature through empiricism.",
    "description_pt": "Um filósofo inglês e frade franciscano que deu ênfase considerável ao estudo da natureza através do empirismo.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Roger Bacon philosopher",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "England"
  },
  {
    "id": "alhazen",
    "name": "Alhazen / Ibn al-Haytham",
    "description": "An Arab mathematician, astronomer, and physicist of the Islamic Golden Age. Referred to as 'the father of modern optics'.",
    "description_pt": "Um matemático, astrônomo e físico árabe da Idade de Ouro Islâmica. Referido como 'o pai da óptica moderna'.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Alhazen optics",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Persia"
  },
  {
    "id": "thomas-aquinas",
    "name": "Santo Tomás de Aquino",
    "description": "An Italian Dominican friar, philosopher, Catholic priest, and Doctor of the Church. An immensely influential philosopher, theologian, and jurist in the tradition of scholasticism.",
    "description_pt": "Um frade dominicano italiano, filósofo, padre católico e Doutor da Igreja. Um filósofo, teólogo e jurista imensamente influente na tradição da escolástica.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Thomas Aquinas philosopher",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Italy"
  },
  {
    "id": "maimonides",
    "name": "Maimônides",
    "description": "A Sephardic Jewish philosopher who became one of the most prolific and influential Torah scholars of the Middle Ages.",
    "description_pt": "Um filósofo judeu sefardita que se tornou um dos mais prolíficos e influentes estudiosos da Torá da Idade Média.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Maimonides philosopher",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Spain/Jewish"
  },
  {
    "id": "dante-alighieri",
    "name": "Dante Alighieri",
    "description": "An Italian poet, writer and philosopher. His Divine Comedy is widely considered the most important poem of the Middle Ages and the greatest literary work in the Italian language.",
    "description_pt": "Um poeta, escritor e filósofo italiano. Sua Divina Comédia é amplamente considerada o poema mais importante da Idade Média e a maior obra literária da língua italiana.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Dante poet",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Italy"
  },
  {
    "id": "chretien-de-troyes",
    "name": "Chrétien de Troyes",
    "description": "A French poet and trouvère known for his work on Arthurian subjects, and for originating the character of Lancelot.",
    "description_pt": "Um poeta e trovador francês conhecido por seu trabalho sobre temas arturianos e por originar o personagem de Lancelote.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Chretien de Troyes poet",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "France"
  },
  {
    "id": "bede",
    "name": "Beda, o Venerável",
    "description": "An English Benedictine monk at the monastery of St. Peter and its companion monastery of St. Paul in the Kingdom of Northumbria of the Angles.",
    "description_pt": "Um monge beneditino inglês no mosteiro de São Pedro e seu mosteiro companheiro de São Paulo no Reino da Nortúmbria dos Anglos.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Bede monk",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "History",
    "field_pt": "História",
    "country": "England"
  },
  {
    "id": "ibn-khaldun",
    "name": "Ibn Khaldun",
    "description": "An Arab sociologist, philosopher, and historian who is widely acknowledged to be one of the greatest social scientists of the Middle Ages.",
    "description_pt": "Um sociólogo, filósofo e historiador árabe que é amplamente reconhecido como um dos maiores cientistas sociais da Idade Média.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Ibn Khaldun historian",
    "era": "Medieval",
    "era_pt": "Medieval",
    "field": "History",
    "field_pt": "História",
    "country": "Tunisia"
  },
  {
    "id": "nikola-tesla",
    "name": "Nikola Tesla",
    "description": "A Serbian-American inventor, electrical engineer, mechanical engineer, and futurist who is best known for his contributions to the design of the modern alternating current (AC) electricity supply system.",
    "description_pt": "Um inventor sérvio-americano, engenheiro elétrico, engenheiro mecânico e futurista, mais conhecido por suas contribuições para o projeto do moderno sistema de fornecimento de eletricidade de corrente alternada (CA).",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Nikola Tesla inventor",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Serbia/USA"
  },
  {
    "id": "nelson-mandela",
    "name": "Nelson Mandela",
    "description": "A South African anti-apartheid revolutionary, political leader and philanthropist who served as President of South Africa from 1994 to 1999.",
    "description_pt": "Um revolucionário anti-apartheid sul-africano, líder político e filantropo que serviu como Presidente da África do Sul de 1994 a 1999.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Nelson Mandela",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "South Africa"
  },
  {
    "id": "winston-churchill",
    "name": "Winston Churchill",
    "description": "A British statesman, army officer, and writer. He was Prime Minister of the United Kingdom from 1940 to 1945, during the Second World War, and again from 1951 to 1955.",
    "description_pt": "Um estadista, oficial do exército e escritor britânico. Ele foi Primeiro-Ministro do Reino Unido de 1940 a 1945, durante a Segunda Guerra Mundial, and novamente de 1951 a 1955.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Winston Churchill",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Politics",
    "field_pt": "Política",
    "country": "England"
  },
  {
    "id": "richard-feynman",
    "name": "Richard Feynman",
    "description": "An American theoretical physicist, known for his work in the path integral formulation of quantum mechanics, the theory of quantum electrodynamics, and the physics of the superfluidity of supercooled liquid helium.",
    "description_pt": "Um físico teórico americano, conhecido por seu trabalho na formulação da integral de caminho da mecânica quântica, a teoria da eletrodinâmica quântica e a física da superfluidez do hélio líquido super-resfriado.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Richard Feynman",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "USA"
  },
  {
    "id": "hannah-arendt",
    "name": "Hannah Arendt",
    "description": "A German-American political philosopher. Her work deals with the nature of power, and the subjects of politics, direct democracy, authority, and totalitarianism.",
    "description_pt": "Uma filósofa política teuto-americana. Sua obra trata da natureza do poder e dos temas da política, democracia direta, autoridade e totalitarismo.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Hannah Arendt",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Germany"
  },
  {
    "id": "michel-foucault",
    "name": "Michel Foucault",
    "description": "A French philosopher, historian of ideas, writer, political activist, and literary critic. Foucault's theories primarily address the relationship between power and knowledge, and how they are used as a form of social control through societal institutions.",
    "description_pt": "Um filósofo francês, historiador das ideias, escritor, ativista político e crítico literário. As teorias de Foucault abordam principalmente a relação entre poder e conhecimento, e como eles são usados como forma de controle social através das instituições da sociedade.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Michel Foucault",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "France"
  },
  {
    "id": "jorge-amado",
    "name": "Jorge Amado",
    "description": "A Brazilian writer of the modernist school. He remains the best known of modern Brazilian writers, with his work having been translated into some 49 languages and popularized in film, notably Dona Flor and Her Two Husbands.",
    "description_pt": "Um escritor brasileiro da escola modernista. Ele continua sendo o mais conhecido dos escritores brasileiros modernos, com sua obra traduzida para cerca de 49 idiomas e popularizada no cinema, notadamente Dona Flor e Seus Dois Maridos.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Jorge Amado",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Brazil"
  },
  {
    "id": "toni-morrison",
    "name": "Toni Morrison",
    "description": "An American novelist. Her first novel, The Bluest Eye, was published in 1970. The critically acclaimed Song of Solomon (1977) brought her national attention and won the National Book Critics Circle Award.",
    "description_pt": "Uma romancista americana. Seu primeiro romance, O Olho Mais Azul, foi publicado em 1970. A aclamada Canção de Salomão (1977) a trouxe à atenção nacional e ganhou o Prêmio do Círculo Nacional de Críticos de Livros.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Toni Morrison",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "USA"
  },
  {
    "id": "eric-hobsbawm",
    "name": "Eric Hobsbawm",
    "description": "A British Marxist historian of the rise of industrial capitalism, socialism and nationalism. His best-known works include his trilogy about the 19th century: The Age of Revolution: Europe 1789–1848, The Age of Capital: 1848–1875 and The Age of Empire: 1875–1914.",
    "description_pt": "Um historiador marxista britânico da ascensão do capitalismo industrial, socialismo e nacionalismo. Suas obras mais conhecidas incluem sua trilogia sobre o século XIX: A Era das Revoluções: Europa 1789–1848, A Era do Capital: 1848–1875 e A Era dos Impérios: 1875–1914.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Eric Hobsbawm",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "History",
    "field_pt": "História",
    "country": "England"
  },
  {
    "id": "howard-zinn",
    "name": "Howard Zinn",
    "description": "An American historian, playwright, and social activist. He was a professor of political science at Boston University. Zinn wrote more than 20 books, including his best-selling and influential A People's History of the United States.",
    "description_pt": "Um historiador, dramaturgo e ativista social americano. Ele foi professor de ciência política na Universidade de Boston. Zinn escreveu mais de 20 livros, incluindo seu best-seller e influente A People's History of the United States.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Howard Zinn",
    "era": "Modern",
    "era_pt": "Moderna",
    "field": "History",
    "field_pt": "História",
    "country": "USA"
  },
  {
    "id": "queen-victoria",
    "name": "Rainha Vitória",
    "description": "Queen of the United Kingdom of Great Britain and Ireland from 20 June 1837 until her death in 1901. Her reign of 63 years and seven months is known as the Victorian era.",
    "description_pt": "Rainha do Reino Unido da Grã-Bretanha e Irlanda de 20 de junho de 1837 até sua morte em 1901. Seu reinado de 63 anos e sete meses é conhecido como a era vitoriana.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Queen Victoria",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "Politics",
    "field_pt": "Política",
    "country": "England"
  },
  {
    "id": "otto-von-bismarck",
    "name": "Otto von Bismarck",
    "description": "A conservative Prussian statesman who masterminded the unification of Germany in 1871 and served as its first chancellor until 1890.",
    "description_pt": "Um estadista prussiano conservador que arquitetou a unificação da Alemanha em 1871 e serviu como seu primeiro chanceler até 1890.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Otto von Bismarck",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Germany"
  },
  {
    "id": "ada-lovelace",
    "name": "Ada Lovelace",
    "description": "An English mathematician and writer, chiefly known for her work on Charles Babbage's proposed mechanical general-purpose computer, the Analytical Engine.",
    "description_pt": "Uma matemática e escritora inglesa, conhecida principalmente por seu trabalho no computador mecânico de uso geral proposto por Charles Babbage, a Máquina Analítica.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Ada Lovelace",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "England"
  },
  {
    "id": "michael-faraday",
    "name": "Michael Faraday",
    "description": "An English scientist who contributed to the study of electromagnetism and electrochemistry. His main discoveries include the principles underlying electromagnetic induction, diamagnetism and electrolysis.",
    "description_pt": "Um cientista inglês que contribuiu para o estudo do eletromagnetismo e da eletroquímica. Suas principais descobertas incluem os princípios subjacentes à indução eletromagnética, diamagnetismo e eletrólise.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Michael Faraday",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "England"
  },
  {
    "id": "james-clerk-maxwell",
    "name": "James Clerk Maxwell",
    "description": "A Scottish scientist in the field of mathematical physics. His most notable achievement was to formulate the classical theory of electromagnetic radiation, bringing together for the first time electricity, magnetism, and light as different manifestations of the same phenomenon.",
    "description_pt": "Um cientista escocês no campo da física matemática. Sua conquista mais notável foi formular a teoria clássica da radiação eletromagnética, reunindo pela primeira vez eletricidade, magnetismo e luz como diferentes manifestações do mesmo fenômeno.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "James Clerk Maxwell",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Scotland"
  },
  {
    "id": "karl-marx",
    "name": "Karl Marx",
    "description": "A German philosopher, economist, historian, sociologist, political theorist, journalist and socialist revolutionary. His best-known titles are the 1848 pamphlet, The Communist Manifesto, and the three-volume Das Kapital.",
    "description_pt": "Um filósofo, economista, historiador, sociólogo, teórico político, jornalista e revolucionário socialista alemão. Seus títulos mais conhecidos são o panfleto de 1848, O Manifesto Comunista, e os três volumes de O Capital.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Karl Marx",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Germany"
  },
  {
    "id": "john-stuart-mill",
    "name": "John Stuart Mill",
    "description": "An English philosopher, political economist, and civil servant. One of the most influential thinkers in the history of classical liberalism, he contributed widely to social theory, political theory, and political economy.",
    "description_pt": "Um filósofo, economista político e funcionário público inglês. Um dos pensadores mais influentes na história do liberalismo clássico, ele contribuiu amplamente para a teoria social, teoria política e economia política.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "John Stuart Mill",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "England"
  },
  {
    "id": "charles-dickens",
    "name": "Charles Dickens",
    "description": "An English writer and social critic. He created some of the world's best-known fictional characters and is regarded by many as the greatest novelist of the Victorian era.",
    "description_pt": "Um escritor e crítico social inglês. Ele criou alguns dos personagens de ficção mais conhecidos do mundo e é considerado por muitos como o maior romancista da era vitoriana.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Charles Dickens",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "England"
  },
  {
    "id": "victor-hugo",
    "name": "Victor Hugo",
    "description": "A French poet, novelist, and dramatist of the Romantic movement. Hugo is considered to be one of the greatest and best-known French writers.",
    "description_pt": "Um poeta, romancista e dramaturgo francês do movimento romântico. Hugo é considerado um dos maiores e mais conhecidos escritores franceses.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Victor Hugo",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "France"
  },
  {
    "id": "lord-acton",
    "name": "Lord Acton",
    "description": "An English Catholic historian, politician, and writer. He was one of the most learned men of his time, and one of the most influential historians of the 19th century.",
    "description_pt": "Um historiador, político e escritor católico inglês. Ele foi um dos homens mais eruditos de seu tempo e um dos historiadores mais influentes do século XIX.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Lord Acton",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "History",
    "field_pt": "História",
    "country": "England"
  },
  {
    "id": "jules-michelet",
    "name": "Jules Michelet",
    "description": "A French historian and a major figure in the historiography of the 19th century. He is known for his monumental work, 'Histoire de France' (History of France).",
    "description_pt": "Um historiador francês e uma figura importante na historiografia do século XIX. Ele é conhecido por sua obra monumental, 'Histoire de France' (História da França).",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Jules Michelet",
    "era": "Victorian",
    "era_pt": "Vitoriana",
    "field": "History",
    "field_pt": "História",
    "country": "France"
  },
  {
    "id": "niccolo-machiavelli",
    "name": "Nicolau Maquiavel",
    "description": "An Italian diplomat, politician, historian, philosopher, and writer of the Renaissance period. He has often been called the father of modern political philosophy and political science.",
    "description_pt": "Um diplomata, político, historiador, filósofo e escritor italiano do período renascentista. Ele tem sido frequentemente chamado de o pai da filosofia política moderna e da ciência política.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Niccolo Machiavelli",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Italy"
  },
  {
    "id": "elizabeth-i",
    "name": "Isabel I",
    "description": "Queen of England and Ireland from 17 November 1558 until her death in 1603. Sometimes called the Virgin Queen, Elizabeth was the last of the five monarchs of the House of Tudor.",
    "description_pt": "Rainha da Inglaterra e Irlanda de 17 de novembro de 1558 até sua morte em 1603. Às vezes chamada de Rainha Virgem, Isabel foi a última dos cinco monarcas da Casa de Tudor.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Elizabeth I",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Politics",
    "field_pt": "Política",
    "country": "England"
  },
  {
    "id": "albrecht-durer",
    "name": "Albrecht Dürer",
    "description": "A German painter, printmaker, and theorist of the German Renaissance. Dürer established his reputation and influence across Europe when he was still in his twenties due to his high-quality woodcut prints.",
    "description_pt": "Um pintor, gravurista e teórico alemão do Renascimento alemão. Dürer estabeleceu sua reputação e influência em toda a Europa quando ainda estava na casa dos vinte anos, devido às suas gravuras em madeira de alta qualidade.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Albrecht Durer",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Germany"
  },
  {
    "id": "galileo-galilei",
    "name": "Galileu Galilei",
    "description": "An Italian astronomer, physicist and engineer, whose discoveries with the telescope revolutionized astronomy and paved the way for the acceptance of the Copernican heliocentric system.",
    "description_pt": "Um astrônomo, físico e engenheiro italiano, cujas descobertas com o telescópio revolucionaram a astronomia e abriram caminho para a aceitação do sistema heliocêntrico copernicano.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Galileo Galilei",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Italy"
  },
  {
    "id": "andreas-vesalius",
    "name": "Andreas Vesalius",
    "description": "A Brabantian anatomist, physician, and author of one of the most influential books on human anatomy, De humani corporis fabrica (On the Fabric of the Human Body).",
    "description_pt": "Um anatomista, médico e autor brabantino de um dos livros mais influentes sobre anatomia humana, De humani corporis fabrica (Sobre a Estrutura do Corpo Humano).",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Andreas Vesalius",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Belgium"
  },
  {
    "id": "michel-de-montaigne",
    "name": "Michel de Montaigne",
    "description": "One of the most significant philosophers of the French Renaissance, known for popularizing the essay as a literary genre.",
    "description_pt": "Um dos filósofos mais significativos do Renascimento francês, conhecido por popularizar o ensaio como gênero literário.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Michel de Montaigne",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "France"
  },
  {
    "id": "giordano-bruno",
    "name": "Giordano Bruno",
    "description": "An Italian Dominican friar, philosopher, mathematician, poet, and cosmological theorist. He is known for his cosmological theories, which conceptually extended the then-novel Copernican model.",
    "description_pt": "Um frade dominicano italiano, filósofo, matemático, poeta e teórico cosmológico. Ele é conhecido por suas teorias cosmológicas, que estenderam conceitualmente o então novo modelo copernicano.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Giordano Bruno",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Italy"
  },
  {
    "id": "luis-de-camoes",
    "name": "Luís de Camões",
    "description": "Portugal's and the Portuguese language's greatest poet. His mastery of verse has been compared to that of Shakespeare, Vondel, Homer, Virgil and Dante.",
    "description_pt": "O maior poeta de Portugal e da língua portuguesa. Sua maestria no verso foi comparada à de Shakespeare, Vondel, Homero, Virgílio e Dante.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Luis de Camoes",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Portugal"
  },
  {
    "id": "francesco-guicciardini",
    "name": "Francesco Guicciardini",
    "description": "An Italian historian and statesman. A friend and critic of Machiavelli, he is considered one of the major political writers of the Italian Renaissance.",
    "description_pt": "Um historiador e estadista italiano. Amigo e crítico de Maquiavel, é considerado um dos maiores escritores políticos do Renascimento italiano.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Francesco Guicciardini",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "History",
    "field_pt": "História",
    "country": "Italy"
  },
  {
    "id": "jean-bodin",
    "name": "Jean Bodin",
    "description": "A French jurist and political philosopher, member of the Parlement of Paris and professor of law in Toulouse. He is best known for his theory of sovereignty.",
    "description_pt": "Um jurista e filósofo político francês, membro do Parlamento de Paris e professor de direito em Toulouse. Ele é mais conhecido por sua teoria da soberania.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Jean Bodin",
    "era": "Renaissance",
    "era_pt": "Renascentista",
    "field": "History",
    "field_pt": "História",
    "country": "France"
  },
  {
    "id": "julius-caesar",
    "name": "Júlio César",
    "description": "A Roman general and statesman who played a critical role in the events that led to the demise of the Roman Republic and the rise of the Roman Empire.",
    "description_pt": "Um general e estadista romano que desempenhou um papel crítico nos eventos que levaram ao fim da República Romana e à ascensão do Império Romano.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Julius Caesar",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Rome"
  },
  {
    "id": "pericles",
    "name": "Péricles",
    "description": "A prominent and influential Greek statesman, orator and general of Athens during its golden age – specifically the time between the Persian and Peloponnesian wars.",
    "description_pt": "Um proeminente e influente estadista, orador e general grego de Atenas durante sua idade de ouro - especificamente o tempo entre as guerras Persas e do Peloponeso.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Pericles athens",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Politics",
    "field_pt": "Política",
    "country": "Athens"
  },
  {
    "id": "archimedes",
    "name": "Arquimedes",
    "description": "A Greek mathematician, physicist, engineer, inventor, and astronomer. He is regarded as one of the leading scientists in classical antiquity.",
    "description_pt": "Um matemático, físico, engenheiro, inventor e astrônomo grego. Ele é considerado um dos principais cientistas da antiguidade clássica.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Archimedes scientist",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Greece"
  },
  {
    "id": "imhotep",
    "name": "Imhotep",
    "description": "An Egyptian chancellor to the pharaoh Djoser, probable architect of the step pyramid, and high priest of the sun god Ra at Heliopolis.",
    "description_pt": "Um chanceler egípcio do faraó Djoser, provável arquiteto da pirâmide de degraus e sumo sacerdote do deus sol Rá em Heliópolis.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Imhotep egypt",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Art & Science",
    "field_pt": "Arte & Ciência",
    "country": "Egypt"
  },
  {
    "id": "hippocrates",
    "name": "Hipócrates",
    "description": "A Greek physician of the Age of Pericles, who is considered one of the most outstanding figures in the history of medicine. He is often referred to as the 'Father of Medicine'.",
    "description_pt": "Um médico grego da Idade de Péricles, considerado uma das figuras mais proeminentes da história da medicina. Ele é frequentemente referido como o 'Pai da Medicina'.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Hippocrates medicine",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Greece"
  },
  {
    "id": "ptolemy",
    "name": "Ptolomeu",
    "description": "A Greco-Roman mathematician, astronomer, geographer and astrologer. He lived in the city of Alexandria in the Roman province of Egypt, under Roman rule.",
    "description_pt": "Um matemático, astrônomo, geógrafo e astrólogo greco-romano. Ele viveu na cidade de Alexandria, na província romana do Egito, sob o domínio romano.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Ptolemy astronomer",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Science",
    "field_pt": "Ciência",
    "country": "Egypt"
  },
  {
    "id": "socrates",
    "name": "Sócrates",
    "description": "A classical Greek (Athenian) philosopher credited as one of the founders of Western philosophy, and as being the first moral philosopher of the Western ethical tradition of thought.",
    "description_pt": "Um filósofo grego clássico (ateniense) creditado como um dos fundadores da filosofia ocidental e como sendo o primeiro filósofo moral da tradição ética de pensamento ocidental.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Socrates philosopher",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "Greece"
  },
  {
    "id": "laozi",
    "name": "Laozi",
    "description": "An ancient Chinese philosopher and writer. He is the reputed author of the Tao Te Ching, the founder of philosophical Taoism, and a deity in religious Taoism and traditional Chinese religions.",
    "description_pt": "Um antigo filósofo e escritor chinês. Ele é o autor reputado do Tao Te Ching, o fundador do taoísmo filosófico e uma divindade no taoísmo religioso e nas religiões tradicionais chinesas.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Laozi philosopher",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Philosophy",
    "field_pt": "Filosofia",
    "country": "China"
  },
  {
    "id": "homer",
    "name": "Homero",
    "description": "The presumed author of the Iliad and the Odyssey, two epic poems that are the central works of ancient Greek literature.",
    "description_pt": "O presumível autor da Ilíada e da Odisseia, dois poemas épicos que são as obras centrais da literatura grega antiga.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Homer poet",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Greece"
  },
  {
    "id": "virgil",
    "name": "Virgílio",
    "description": "An ancient Roman poet of the Augustan period. He wrote three of the most famous poems in Latin literature: the Eclogues, the Georgics, and the epic Aeneid.",
    "description_pt": "Um antigo poeta romano do período augustano. Ele escreveu três dos poemas mais famosos da literatura latina: as Éclogas, as Geórgicas e a épica Eneida.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Virgil poet",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "Literature",
    "field_pt": "Literatura",
    "country": "Rome"
  },
  {
    "id": "herodotus",
    "name": "Heródoto",
    "description": "A Greek writer who invented the field of study known today as 'history'. He was the first writer to perform systematic investigation of historical events.",
    "description_pt": "Um escritor grego que inventou o campo de estudo conhecido hoje como 'história'. Ele foi o primeiro escritor a realizar uma investigação sistemática de eventos históricos.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Herodotus history",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "History",
    "field_pt": "História",
    "country": "Greece"
  },
  {
    "id": "sima-qian",
    "name": "Sima Qian",
    "description": "A Chinese historian of the early Han dynasty. He is considered the father of Chinese historiography for his Records of the Grand Historian.",
    "description_pt": "Um historiador chinês do início da dinastia Han. Ele é considerado o pai da historiografia chinesa por seus Registros do Grande Historiador.",
    "image": "https://placehold.co/400x400.png",
    "aiHint": "Sima Qian historian",
    "era": "Antiquity",
    "era_pt": "Antiguidade",
    "field": "History",
    "field_pt": "História",
    "country": "China"
  }
]
